-- =====================================================================
-- Migración de queries: queries.model.ts → KRC_QUERY (SCENARIO=K)
-- Generado: 2026-05-08T15:33:15.126Z
-- Total INSERTs: 32
-- 
-- IMPORTANTE: revisar la salida del SELECT final ANTES de hacer COMMIT.
-- Si k_count != 32, ejecutar ROLLBACK en lugar de COMMIT.
-- =====================================================================

START TRANSACTION;

-- GETPROD → getProducts()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GETPROD',
    'SELECT
        PROD.PRODUCT_ID
        , PROD.PRODUCT_CODE
        , PROD.PRODUCT_CATEGORY_ID
        , CAT.PRODUCT_CATEGORY
        , PROD.PRODUCT_NAME
        , PROD.PRODUCT_NAME_INTERNAL
        , PROD.PRODUCT_DESCRIPTION
        , PROD.BRAND_ID
        , BRAND.BRAND
        , PROD.MIN_QUANTITY_SELL
        , PROD.LANGUAGE_CODE
        , PROD.PRODUCT_PRICE/10000 PRODUCT_PRICE
        , PROD.TAX_ID
        , PROD.CURRENCY_ID
        , PROD.UNIT_ID
        , DMD_UNIT.DES_UNIT
        , PROD.WEEKS_WARNING
        , PROD.QUANTITY_MIN_PRICE
        , PROD.QUANTITY_MAX_PRICE
        , PROD.TYPE_DAY_DELIVERY
        , DMD_DELIVERY_TYPE.DES_DELIVERY_TYPE
        , PROD.MIN_DAYS_DELIVERY
        , PROD.MAX_DAYS_DELIVERY
        , PROD.REMARK
        , PROD.DAYS_DELIVERY
        , PROD.PRODUCT_TYPE_ID
        , PROD.PROVIDER_ID
        , PERSONE.PERSONE_NAME
        , PROD.PARTNER_ID
        , PARTNER.PERSONE_NAME PARTNER_NAME
        , PROD.EFF_DATE
        , PROD.EXP_DATE
        , PROD.DAYS_EXP
        , PRODUCT_TYPE.BAN_EXPIRES
        , PRODUCT_TYPE.BAN_INVENTORY
        , PROD.SOURCE_ID
        , PROD.NUM_IMAGES
        , PROD.NUM_VIDEOS
    FROM
        KRC_PRODUCT PROD
        LEFT JOIN KRC_PRODUCT_CATEGORY CAT
        ON (CAT.PRODUCT_CATEGORY_ID = PROD.PRODUCT_CATEGORY_ID AND CAT.STATUS_ID = ''A'' )
        LEFT OUTER JOIN KRC_BRAND BRAND
        ON (BRAND.BRAND_ID = PROD.BRAND_ID AND BRAND.STATUS_ID = ''A'')
        LEFT OUTER JOIN KRC_TAX_TYPE TAX
        ON (TAX.TAX_ID = PROD.TAX_ID)
        LEFT OUTER JOIN DMD_UNIT
        ON (DMD_UNIT.CVE_UNIT = PROD.UNIT_ID)
        LEFT OUTER JOIN DMD_DELIVERY_TYPE
        ON (PROD.TYPE_DAY_DELIVERY = DMD_DELIVERY_TYPE.CVE_DELIVERY_TYPE)
        LEFT OUTER JOIN KRC_PRODUCT_TYPE PRODUCT_TYPE
        ON (PROD.PRODUCT_TYPE_ID = PRODUCT_TYPE.PRODUCT_TYPE_ID)
        LEFT OUTER JOIN KRC_PERSONE_IDENTITY PERSONE
        ON (PROD.PROVIDER_ID = PERSONE.PERSONE_ID AND PERSONE.STATUS_ID = ''A'')
        LEFT OUTER JOIN KRC_PERSONE_IDENTITY PARTNER
        ON (PROD.PARTNER_ID = PARTNER.PERSONE_ID AND PARTNER.STATUS_ID = ''A'')
    WHERE
        PROD.STATUS_ID = ''A'' and PROD.PRODUCT_ID <= 10
    ;',
    'Catálogo completo de productos (top 10)',
    'SELECT con todos los JOINs sobre KRC_PRODUCT, limitado a PRODUCT_ID <= 10',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Catálogo demo'
);

-- GTPRODAVL → queryGetProductsAvailable()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRODAVL',
    'SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, BRAND, NUM_IMAGES, NUM_VIDEOS, AVAIL, PRODUCT_PRICE, PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL, TAX_ID, TAX_APPLY, case when ID_UNIT = ''LT'' then ''Lt''    when ID_UNIT = ''UNI'' then ''Ud''    when ID_UNIT = ''KG'' then ''Kg''  end AS ID_UNIT, REMARK, MIN_QUANTITY_SELL FROM (select A.PRODUCT_ID, C.PRODUCT_NAME, C.PRODUCT_DESCRIPTION, D.PRODUCT_TYPE, C.BRAND, C.NUM_IMAGES, C.NUM_VIDEOS, ROUND(SUM(QUANTITY)) AVAIL, ROUND(max(PRODUCT_PRICE/10000), 2) PRODUCT_PRICE, E.PERSONE_ID, E.PERSONE_NAME, E.BUSINESS_NAME, E.EMAIL, C.TAX_ID, F.TAX_APPLY, TIP_UNIDAD.ID_UNIT, C.REMARK, C.MIN_QUANTITY_SELL , ROW_NUMBER() OVER (PARTITION BY C.PRODUCT_CATEGORY_ID, E.PERSONE_NAME ORDER BY IFNULL(C.MODIFY_DATE, C.CREATE_DATE) DESC) AS RN FROM (        SELECT PRODUCT_AVAIL_ID,ORDER_ID,PRODUCT_ID,QUANTITY,PRODUCT_PRICE,PRODUCT_PRICE_PAID,PREDICTABLE_FINISH_DATE,        RESET_MANUAL_DATE,CALIBRATE_DATE,CREATE_DATE,EXP_DATE,MODIFY_DATE,STATUS_DATE,USER_CREATE_ID,USER_MODIFY_ID,        METHOD,PRODUCT_CATEGORY_ID,PARTNER_ID,PARTNER_NAME         FROM KRC_PRODUCT_AVAIL     ) A INNER JOIN (  SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE_ID, BRAND, REMARK, NUM_IMAGES, NUM_VIDEOS, PROVIDER_ID, TAX_ID, UNIT_ID, PRODUCT_CATEGORY_ID, IFNULL(MIN_QUANTITY_SELL, 1) AS MIN_QUANTITY_SELL, MODIFY_DATE, CREATE_DATE FROM KRC_PRODUCT WHERE STATUS_ID=''A'' GROUP BY PRODUCT_ID) C ON (A.PRODUCT_ID = C.PRODUCT_ID) LEFT OUTER JOIN (SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE FROM KRC_PRODUCT_TYPE WHERE STATUS_ID = ''A'') D ON (C.PRODUCT_TYPE_ID = D.PRODUCT_TYPE_ID) LEFT OUTER JOIN (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) TIP_UNIDAD ON (C.UNIT_ID = TIP_UNIDAD.CVE_UNIT) LEFT OUTER JOIN (SELECT PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL FROM KRC_PERSONE_IDENTITY WHERE STATUS_ID = ''A'' AND PERSONE_TYPE = ''P'') E ON (C.PROVIDER_ID = E.PERSONE_ID) LEFT OUTER JOIN (SELECT TAX_ID, TAX_APPLY FROM KRC_TAX_TYPE) F ON (C.TAX_ID = F.TAX_ID)  WHERE A.QUANTITY>0 GROUP BY A.PRODUCT_ID, PRODUCT_NAME ORDER BY PRODUCT_NAME) AA WHERE AA.RN=1;',
    'Productos disponibles con stock',
    'SELECT productos disponibles agregando QUANTITY > 0 sobre KRC_PRODUCT_AVAIL',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Productos disponibles (genérico)'
);

-- GTPRODAVPT → queryGetProductsAvailableWithPartnerId()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRODAVPT',
    'SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE, BRAND, NUM_IMAGES, NUM_VIDEOS, PRODUCT_PRICE, ROUND(PRODUCT_PRICE*(1+TAX_APPLY/100),2) TOTAL_BEFORE_DISCOUNT, ROUND(PRODUCT_PRICE_DISCOUNTED*(TAX_APPLY/100),2) TAX_AMOUNT, PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL, TAX_ID, TAX_APPLY, PRODUCT_PRICE_DISCOUNTED, ROUND(PRODUCT_PRICE_DISCOUNTED*(1+TAX_APPLY/100),2) TOTAL_AMOUNT , (PRODUCT_PRICE-PRODUCT_PRICE_DISCOUNTED) DISCOUNT_AMOUNT, case when ID_UNIT = ''LT'' then ''Lt''    when ID_UNIT = ''UNI'' then ''Ud''    when ID_UNIT = ''KG'' then ''Kg''  end AS ID_UNIT, REMARK, MIN_QUANTITY_SELL, PARTNER_ID, PARTNER_NAME, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE, PRODUCT_CATEGORY_ID, RN FROM (select A.PRODUCT_ID, A.PRODUCT_CODE, A.PRODUCT_NAME, A.PRODUCT_DESCRIPTION, D.PRODUCT_TYPE, A.BRAND, A.NUM_IMAGES, A.NUM_VIDEOS, A.PRODUCT_PRICE PRODUCT_PRICE, A.PRODUCT_PRICE_FINAL PRODUCT_PRICE_DISCOUNTED, E.PERSONE_ID, E.PERSONE_NAME, E.BUSINESS_NAME, E.EMAIL, A.TAX_ID, F.TAX_APPLY, TIP_UNIDAD.ID_UNIT, A.REMARK, A.MIN_QUANTITY_SELL, A.PRODUCT_NAME_LONG, A.PARTNER_ID, A.PARTNER_NAME , A.MODIFY_DATE, A.CREATE_DATE , A.QUANTITY_MIN_PRICE,  A.QUANTITY_MAX_PRICE, A.PRODUCT_CATEGORY_ID, ROW_NUMBER() OVER (PARTITION BY A.PRODUCT_NAME, E.PERSONE_NAME ORDER BY A.PARTNER_ID DESC, IFNULL(A.MODIFY_DATE, A.CREATE_DATE) DESC, A.PRODUCT_PRICE_FINAL DESC, A.PRODUCT_ID DESC) AS RN FROM (        SELECT R.PRODUCT_ID, R.PRODUCT_CODE, R.PRODUCT_NAME_INTERNAL PRODUCT_NAME, R.PRODUCT_NAME PRODUCT_NAME_LONG, R.PRODUCT_DESCRIPTION, R.PRODUCT_TYPE_ID, R.BRAND, R.REMARK, R.NUM_IMAGES        , R.NUM_VIDEOS, R.PROVIDER_ID, R.TAX_ID, R.PRODUCT_PRICE , R.PRODUCT_PRICE_FINAL, R.PARTNER_ID, R.PARTNER_NAME         , R.UNIT_ID, R.PRODUCT_CATEGORY_ID, IFNULL(R.MIN_QUANTITY_SELL, 1) AS MIN_QUANTITY_SELL         , R.MODIFY_DATE, R.CREATE_DATE, R.QUANTITY_MIN_PRICE, R.QUANTITY_MAX_PRICE         FROM KRC_PRODUCT R         INNER JOIN (SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE FROM KRC_PRODUCT_TYPE WHERE STATUS_ID = ''A'' AND PRODUCT_TYPE_CODE NOT IN (''ASCEN'',''COUMI'',''ENERG'',''SEGUR'',''PERSO'',''SEGUR'')) T         ON (R.PRODUCT_TYPE_ID = T.PRODUCT_TYPE_ID)        WHERE R.STATUS_ID=''A'' AND R.PRODUCT_CODE <> '''' AND R.PARTNER_ID IN (1, $1)   ) A LEFT OUTER JOIN (SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE FROM KRC_PRODUCT_TYPE WHERE STATUS_ID = ''A'') D ON (A.PRODUCT_TYPE_ID = D.PRODUCT_TYPE_ID) LEFT OUTER JOIN (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) TIP_UNIDAD ON (A.UNIT_ID = TIP_UNIDAD.CVE_UNIT) LEFT OUTER JOIN (SELECT PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL FROM KRC_PERSONE_IDENTITY WHERE STATUS_ID = ''A'' AND PERSONE_TYPE = ''P'') E ON (A.PROVIDER_ID = E.PERSONE_ID) LEFT OUTER JOIN (SELECT TAX_ID, TAX_APPLY FROM KRC_TAX_TYPE) F ON (A.TAX_ID = F.TAX_ID) ORDER BY PRODUCT_NAME) AA WHERE (CASE WHEN $1 < 10000 THEN PARTNER_ID IN (1,$1) ELSE PARTNER_ID IN ($1) END ) ORDER BY PRODUCT_CATEGORY_ID, PERSONE_NAME, PARTNER_ID DESC, RN;',
    'Productos disponibles para partner',
    'SELECT productos disponibles filtrados por PARTNER_ID = $1 (partner 1 + partner del usuario)',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Listado tras login'
);

-- GTPRODAVNP → queryGetProductsAvailableWithOutPartnerId()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRODAVNP',
    'SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE, BRAND, NUM_IMAGES, NUM_VIDEOS, PRODUCT_PRICE, ROUND(PRODUCT_PRICE*(1+TAX_APPLY/100),2) TOTAL_BEFORE_DISCOUNT, ROUND(PRODUCT_PRICE_DISCOUNTED*(TAX_APPLY/100),2) TAX_AMOUNT, PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL, TAX_ID, TAX_APPLY, PRODUCT_PRICE_DISCOUNTED, ROUND(PRODUCT_PRICE_DISCOUNTED*(1+TAX_APPLY/100),2) TOTAL_AMOUNT , (PRODUCT_PRICE-PRODUCT_PRICE_DISCOUNTED) DISCOUNT_AMOUNT, case when ID_UNIT = ''LT'' then ''Lt''    when ID_UNIT = ''UNI'' then ''Ud''    when ID_UNIT = ''KG'' then ''Kg''  end AS ID_UNIT, REMARK, MIN_QUANTITY_SELL, PARTNER_ID, PARTNER_NAME, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE, PRODUCT_CATEGORY_ID, RN FROM (select A.PRODUCT_ID, A.PRODUCT_CODE, A.PRODUCT_NAME, A.PRODUCT_DESCRIPTION, D.PRODUCT_TYPE, A.BRAND, A.NUM_IMAGES, A.NUM_VIDEOS, A.PRODUCT_PRICE PRODUCT_PRICE, A.PRODUCT_PRICE_FINAL PRODUCT_PRICE_DISCOUNTED, E.PERSONE_ID, E.PERSONE_NAME, E.BUSINESS_NAME, E.EMAIL, A.TAX_ID, F.TAX_APPLY, TIP_UNIDAD.ID_UNIT, A.REMARK, A.MIN_QUANTITY_SELL, A.PRODUCT_NAME_LONG, A.PARTNER_ID, A.PARTNER_NAME , A.MODIFY_DATE, A.CREATE_DATE , A.QUANTITY_MIN_PRICE,  A.QUANTITY_MAX_PRICE, A.PRODUCT_CATEGORY_ID, ROW_NUMBER() OVER (PARTITION BY A.PRODUCT_NAME, E.PERSONE_NAME ORDER BY A.PARTNER_ID DESC, IFNULL(A.MODIFY_DATE, A.CREATE_DATE) DESC, A.PRODUCT_PRICE_FINAL DESC, A.PRODUCT_ID DESC) AS RN FROM (        SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME_INTERNAL PRODUCT_NAME, PRODUCT_NAME PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE_ID, BRAND, REMARK, NUM_IMAGES        , NUM_VIDEOS, PROVIDER_ID, TAX_ID, PRODUCT_PRICE , PRODUCT_PRICE_FINAL, PARTNER_ID, PARTNER_NAME        , UNIT_ID, PRODUCT_CATEGORY_ID, IFNULL(MIN_QUANTITY_SELL, 1) AS MIN_QUANTITY_SELL        , MODIFY_DATE, CREATE_DATE, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE        FROM KRC_PRODUCT        WHERE STATUS_ID=''A'' AND PARTNER_ID = 1   ) A LEFT OUTER JOIN (SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE FROM KRC_PRODUCT_TYPE WHERE STATUS_ID = ''A'' AND PRODUCT_TYPE_CODE NOT IN (''ASCEN'',''COUMI'',''ENERG'',''SEGUR'',''PERSO'',''SEGUR'')) D ON (A.PRODUCT_TYPE_ID = D.PRODUCT_TYPE_ID) LEFT OUTER JOIN (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) TIP_UNIDAD ON (A.UNIT_ID = TIP_UNIDAD.CVE_UNIT) LEFT OUTER JOIN (SELECT PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL FROM KRC_PERSONE_IDENTITY WHERE STATUS_ID = ''A'' AND PERSONE_TYPE = ''P'') E ON (A.PROVIDER_ID = E.PERSONE_ID) LEFT OUTER JOIN (SELECT TAX_ID, TAX_APPLY FROM KRC_TAX_TYPE) F ON (A.TAX_ID = F.TAX_ID) ORDER BY PRODUCT_NAME) AA ORDER BY PRODUCT_CATEGORY_ID, PERSONE_NAME, PARTNER_ID DESC, RN;',
    'Productos disponibles sin login',
    'SELECT productos disponibles del partner por defecto (PARTNER_ID = 1)',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Listado sin login'
);

-- GTPRODAVPR → getProductAvailWithProductId()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRODAVPR',
    'SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE, BRAND, NUM_IMAGES, NUM_VIDEOS, PRODUCT_PRICE, ROUND(PRODUCT_PRICE*(1+TAX_APPLY/100),2) TOTAL_BEFORE_DISCOUNT, ROUND(PRODUCT_PRICE_DISCOUNTED*(TAX_APPLY/100),2) TAX_AMOUNT, PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL, TAX_ID, TAX_APPLY, PRODUCT_PRICE_DISCOUNTED, ROUND(PRODUCT_PRICE_DISCOUNTED*(1+TAX_APPLY/100),2) TOTAL_AMOUNT , (PRODUCT_PRICE-PRODUCT_PRICE_DISCOUNTED) DISCOUNT_AMOUNT, case when ID_UNIT = ''LT'' then ''Lt''    when ID_UNIT = ''UNI'' then ''Ud''    when ID_UNIT = ''KG'' then ''Kg''  end AS ID_UNIT, REMARK, MIN_QUANTITY_SELL, PARTNER_ID, PARTNER_NAME, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE, PRODUCT_CATEGORY_ID, RN FROM (select A.PRODUCT_ID, A.PRODUCT_CODE, A.PRODUCT_NAME, A.PRODUCT_DESCRIPTION, D.PRODUCT_TYPE, A.BRAND, A.NUM_IMAGES, A.NUM_VIDEOS, A.PRODUCT_PRICE PRODUCT_PRICE, A.PRODUCT_PRICE_FINAL PRODUCT_PRICE_DISCOUNTED, E.PERSONE_ID, E.PERSONE_NAME, E.BUSINESS_NAME, E.EMAIL, A.TAX_ID, F.TAX_APPLY, TIP_UNIDAD.ID_UNIT, A.REMARK, A.MIN_QUANTITY_SELL, A.PRODUCT_NAME_LONG, A.PARTNER_ID, A.PARTNER_NAME , A.MODIFY_DATE, A.CREATE_DATE , A.QUANTITY_MIN_PRICE,  A.QUANTITY_MAX_PRICE, A.PRODUCT_CATEGORY_ID, ROW_NUMBER() OVER (PARTITION BY A.PRODUCT_CATEGORY_ID, E.PERSONE_NAME ORDER BY A.PARTNER_ID DESC, IFNULL(A.MODIFY_DATE, A.CREATE_DATE) DESC, A.PRODUCT_PRICE_FINAL DESC, A.PRODUCT_ID DESC) AS RN FROM (        SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME_INTERNAL PRODUCT_NAME, PRODUCT_NAME PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE_ID, BRAND, REMARK, NUM_IMAGES        , NUM_VIDEOS, PROVIDER_ID, TAX_ID, PRODUCT_PRICE , PRODUCT_PRICE_FINAL, PARTNER_ID, PARTNER_NAME        , UNIT_ID, PRODUCT_CATEGORY_ID, IFNULL(MIN_QUANTITY_SELL, 1) AS MIN_QUANTITY_SELL         , MODIFY_DATE, CREATE_DATE, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE        FROM KRC_PRODUCT        WHERE STATUS_ID=''A'' AND PRODUCT_ID = $1   ) A LEFT OUTER JOIN (SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE FROM KRC_PRODUCT_TYPE WHERE STATUS_ID = ''A'') D ON (A.PRODUCT_TYPE_ID = D.PRODUCT_TYPE_ID) LEFT OUTER JOIN (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) TIP_UNIDAD ON (A.UNIT_ID = TIP_UNIDAD.CVE_UNIT) LEFT OUTER JOIN (SELECT PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL FROM KRC_PERSONE_IDENTITY WHERE STATUS_ID = ''A'' AND PERSONE_TYPE = ''P'') E ON (A.PROVIDER_ID = E.PERSONE_ID) LEFT OUTER JOIN (SELECT TAX_ID, TAX_APPLY FROM KRC_TAX_TYPE) F ON (A.TAX_ID = F.TAX_ID) ORDER BY PRODUCT_NAME) AA ORDER BY PRODUCT_CATEGORY_ID, PERSONE_NAME, PARTNER_ID DESC, RN;',
    'Detalle de producto disponible',
    'SELECT producto disponible filtrado por PRODUCT_ID = $1',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Detalle de producto'
);

-- GTPRCHSEQ → queryPurchaseSequence()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRCHSEQ',
    'select KRRI.nextval(''SEQ_PURCHASE'') ORDER_ID, CAST(date_format(CONVERT_TZ( sysdate(), ''UTC'', ''Europe/Paris''),''%Y%m%d'') AS UNSIGNED) CURRENT_DAY;',
    'Siguiente valor de SEQ_PURCHASE',
    'Devuelve nextval de SEQ_PURCHASE y la fecha actual',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Crear nueva compra'
);

-- GTPRCHUSR → queryGetPurchaseByUserId()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRCHUSR',
    'SELECT ORDER_ID, PROVIDER_NAME, BUYER_NAME, SHOW_NAME, CASE WHEN COUNT(DISTINCT STATUS_NAME)=1 THEN max(STATUS_NAME)    ELSE ''VARIOS'' END ALL_STATUS, CASE WHEN COUNT(DISTINCT STATUS_ID)=1 THEN max(STATUS_ID)    ELSE ''VARIOS'' END STATUS_ID, COUNT(DISTINCT STATUS_NAME) NUM_STATUS, NVL(SUM(CASE WHEN NEW_QUANTITY IS NULL THEN QUANTITY ELSE NEW_QUANTITY END), 0) ITEMS, MAX(SITUACION) SITUACION, NVL(SUM(TOTAL_AMOUNT), 0) TOTAL_AMOUNT, NVL(SUM(TAX_AMOUNT), 0) TAX_AMOUNT, NVL(SUM(DISCOUNT_AMOUNT), 0) DISCOUNT_AMOUNT, NVL(SUM(PRODUCT_PRICE_FINAL), 0) PRODUCT_PRICE_FINAL , NVL(SUM(PRODUCT_PRICE), 0) PRODUCT_PRICE , NVL(SUM(TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX), 0) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX , NVL(SUM(TOTAL_AFTER_DISCOUNT_WITHOUT_TAX), 0) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, MAX(ORDER_DATE) ORDER_DATE FROM (    SELECT ORDER_ID, A.PRODUCT_NAME, A.PRODUCT_ID, A.PROVIDER_NAME    , CASE WHEN D.PARTNER_ID=1 AND J.PERSONE_TYPE=''P'' THEN J.PERSONE_NAME           ELSE D.PARTNER_NAME END BUYER_NAME    , CASE WHEN D.PARTNER_ID=1 AND J.PERSONE_TYPE=''P'' THEN J.PERSONE_NAME           WHEN J.PERSONE_TYPE = ''P'' THEN D.PARTNER_NAME           ELSE A.PROVIDER_NAME END SHOW_NAME    , CASE WHEN A.STATUS_ID IN (''E'',''F'',''P'',''S'',''O'',''D'') THEN ''ABIERTO''        ELSE ''CERRADO'' END SITUACION    , A.TOTAL_AMOUNT    , A.TAX_AMOUNT    , A.DISCOUNT_AMOUNT    , (A.PRODUCT_PRICE - (A.DISCOUNT_AMOUNT/A.QUANTITY)) PRODUCT_PRICE_FINAL    , A.QUANTITY, A.NEW_QUANTITY, B.TAX_APPLY, C.STATUS_ID, C.STATUS_NAME, A.PRODUCT_PRICE     , (A.QUANTITY * A.PRODUCT_PRICE) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX     , ((A.QUANTITY * A.PRODUCT_PRICE) + A.DISCOUNT_AMOUNT) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, A.ORDER_DATE    FROM KRC_PURCHASE A, KRC_TAX_TYPE B,          (SELECT STATUS_OBJECT_ID STATUS_ID, STATUS_NAME FROM KRC_STATUS GROUP BY STATUS_OBJECT_ID, STATUS_NAME) C          ,KRC_PRODUCT D, KRC_PERSONE_IDENTITY E, KRC_PERSONE_IDENTITY H          , (SELECT * FROM (SELECT PERSONE_ID, PERSONE_TYPE, PERSONE_NAME, USER_ID, PARTNER_NAME, PARTNER_ID             , ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY PERSONE_ID)  AS RN  FROM KRC_PERSONE_IDENTITY  ) BB WHERE RN=1) J    WHERE       (A.ORDER_DATE >= DATE_ADD(CURRENT_DATE(), interval -2 MONTH) OR A.STATUS_ID IN (''E'',''F'',''P'',''S'',''O'',''D''))      AND A.TAX_ID=B.TAX_ID AND A.STATUS_ID=C.STATUS_ID AND A.USER_CREATE_ID = E.USER_ID      AND A.PRODUCT_ID=D.PRODUCT_ID AND D.PROVIDER_ID = H.PERSONE_ID      AND $1 = J.USER_ID      AND (A.USER_CREATE_ID = $1         OR $1 IN (SELECT I.USER_ID                     FROM KRC_PERSONE_IDENTITY I WHERE I.STATUS_ID = ''A'' AND I.PARTNER_ID = E.PARTNER_ID                    GROUP BY I.USER_ID                 )        OR $1 IN (SELECT F.USER_ID                    FROM KRC_PERSONE_IDENTITY F, KRR_USER_ROLE G                    WHERE F.STATUS_ID = ''A'' AND F.USER_ID=G.USER_ID AND G.ROLE_ID=2 AND NVL(F.PARTNER_ID,1) != 1                    AND F.PARTNER_ID = H.PARTNER_ID                    GROUP BY F.USER_ID                 )        )    ) AA GROUP BY ORDER_ID, PROVIDER_NAME, BUYER_NAME, SHOW_NAME;',
    'Compras del usuario',
    'Lista compras del usuario o las que pueda ver según PARTNER_ID/ROLE',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Pantalla "Mis compras"'
);

-- GTPRCHUSRR → queryGetPurchaseByUserIdRange()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRCHUSRR',
    'SELECT ORDER_ID, PROVIDER_NAME, BUYER_NAME, SHOW_NAME, CASE WHEN COUNT(DISTINCT STATUS_NAME)=1 THEN max(STATUS_NAME)    ELSE ''VARIOS'' END ALL_STATUS, CASE WHEN COUNT(DISTINCT STATUS_ID)=1 THEN max(STATUS_ID)    ELSE ''VARIOS'' END STATUS_ID, COUNT(DISTINCT STATUS_NAME) NUM_STATUS, NVL(SUM(CASE WHEN NEW_QUANTITY IS NULL THEN QUANTITY ELSE NEW_QUANTITY END), 0) ITEMS, MAX(SITUACION) SITUACION, NVL(SUM(TOTAL_AMOUNT), 0) TOTAL_AMOUNT, NVL(SUM(TAX_AMOUNT), 0) TAX_AMOUNT, NVL(SUM(DISCOUNT_AMOUNT), 0) DISCOUNT_AMOUNT, NVL(SUM(PRODUCT_PRICE_FINAL), 0) PRODUCT_PRICE_FINAL , NVL(SUM(PRODUCT_PRICE), 0) PRODUCT_PRICE , NVL(SUM(TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX), 0) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX , NVL(SUM(TOTAL_AFTER_DISCOUNT_WITHOUT_TAX), 0) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, MAX(ORDER_DATE) ORDER_DATE FROM (    SELECT ORDER_ID, A.PRODUCT_NAME, A.PRODUCT_ID, A.PROVIDER_NAME    , CASE WHEN D.PARTNER_ID=1 AND J.PERSONE_TYPE=''P'' THEN J.PERSONE_NAME           ELSE D.PARTNER_NAME END BUYER_NAME    , CASE WHEN D.PARTNER_ID=1 AND J.PERSONE_TYPE=''P'' THEN J.PERSONE_NAME           WHEN J.PERSONE_TYPE = ''P'' THEN D.PARTNER_NAME           ELSE A.PROVIDER_NAME END SHOW_NAME    , CASE WHEN A.STATUS_ID IN (''E'',''F'',''P'',''S'',''O'',''D'') THEN ''ABIERTO''        ELSE ''CERRADO'' END SITUACION    , A.TOTAL_AMOUNT    , A.TAX_AMOUNT    , A.DISCOUNT_AMOUNT    , (A.PRODUCT_PRICE - (A.DISCOUNT_AMOUNT/A.QUANTITY)) PRODUCT_PRICE_FINAL    , A.QUANTITY, A.NEW_QUANTITY, B.TAX_APPLY, C.STATUS_ID, C.STATUS_NAME, A.PRODUCT_PRICE     , (A.QUANTITY * A.PRODUCT_PRICE) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX     , ((A.QUANTITY * A.PRODUCT_PRICE) + A.DISCOUNT_AMOUNT) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, A.ORDER_DATE    FROM KRC_PURCHASE A, KRC_TAX_TYPE B,          (SELECT STATUS_OBJECT_ID STATUS_ID, STATUS_NAME FROM KRC_STATUS GROUP BY STATUS_OBJECT_ID, STATUS_NAME) C          ,KRC_PRODUCT D, KRC_PERSONE_IDENTITY E, KRC_PERSONE_IDENTITY H          , (SELECT * FROM (SELECT PERSONE_ID, PERSONE_TYPE, PERSONE_NAME, USER_ID, PARTNER_NAME, PARTNER_ID             , ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY PERSONE_ID)  AS RN  FROM KRC_PERSONE_IDENTITY  ) BB WHERE RN=1) J    WHERE       ((A.ORDER_DATE BETWEEN $2 AND $3 AND A.STATUS_ID IN (''A'',''N'')) OR A.STATUS_ID IN (''E'',''F'',''P'',''S'',''O'',''D''))      AND A.TAX_ID=B.TAX_ID AND A.STATUS_ID=C.STATUS_ID AND A.USER_CREATE_ID = E.USER_ID      AND A.PRODUCT_ID=D.PRODUCT_ID AND D.PROVIDER_ID = H.PERSONE_ID      AND $1 = J.USER_ID      AND (A.USER_CREATE_ID = $1         OR $1 IN (SELECT I.USER_ID                     FROM KRC_PERSONE_IDENTITY I WHERE I.STATUS_ID = ''A'' AND I.PARTNER_ID = E.PARTNER_ID                    GROUP BY I.USER_ID                 )        OR $1 IN (SELECT F.USER_ID                    FROM KRC_PERSONE_IDENTITY F, KRR_USER_ROLE G                    WHERE F.STATUS_ID = ''A'' AND F.USER_ID=G.USER_ID AND G.ROLE_ID=2 AND NVL(F.PARTNER_ID,1) != 1                    AND F.PARTNER_ID = H.PARTNER_ID                    GROUP BY F.USER_ID                 )        )    ) AA GROUP BY ORDER_ID, PROVIDER_NAME, BUYER_NAME, SHOW_NAME;',
    'Compras del usuario (rango fechas para cerradas)',
    'Como GTPRCHUSR pero las cerradas (A,N) se filtran por ORDER_DATE BETWEEN $2 AND $3',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Histórico "Servidos/Anulados"'
);

-- GTPRCHLN → queryGetPurchaseLinesByOrderId()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRCHLN',
    'SELECT NVL(ORDER_ID, -1) ORDER_ID, NVL(PROVIDER_NAME, '''') PROVIDER_NAME, NVL(PRODUCT_ID, '''') PRODUCT_ID, PRODUCT_CODE, NVL(PRODUCT_NAME, '''') PRODUCT_NAME, CASE WHEN COUNT(DISTINCT STATUS_NAME)=1 THEN NVL(max(STATUS_NAME), '''')    ELSE ''VARIOS'' END ALL_STATUS, CASE WHEN COUNT(DISTINCT STATUS_ID)=1 THEN NVL(max(STATUS_ID), '''')    ELSE ''VARIOS'' END STATUS_ID, COUNT(DISTINCT STATUS_NAME) NUM_STATUS, NVL(max(BAN_PRICE), '''') BAN_PRICE, NVL(max(BAN_QUANTITY), '''') BAN_QUANTITY, NVL(SUM(QUANTITY), 0) ITEMS, case when ID_UNIT = ''LT'' then ''Lt''  when ID_UNIT = ''UNI'' then ''Ud''  when ID_UNIT = ''KG'' then ''Kg''end AS ID_UNIT, NVL(SUM(NEW_QUANTITY), -1) NEW_QUANTITY, NVL(SUM(NEW_PRODUCT_PRICE_FINAL), -1) NEW_PRODUCT_PRICE_FINAL , NVL(MAX(BAN_OFICIAL_PRICE), '''') BAN_OFICIAL_PRICE, NVL(MAX(SITUACION), '''') SITUACION, NVL(SUM(TOTAL_AMOUNT), 0) TOTAL_AMOUNT, NVL(SUM(TAX_AMOUNT), 0) TAX_AMOUNT, NVL(SUM(DISCOUNT_AMOUNT), 0) DISCOUNT_AMOUNT, NVL(SUM(PRODUCT_PRICE_FINAL), 0) PRODUCT_PRICE_FINAL , NVL(SUM(PRODUCT_PRICE),0) PRODUCT_PRICE , NVL(SUM(TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX), 0) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX , NVL(SUM(TOTAL_AFTER_DISCOUNT_WITHOUT_TAX), 0) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, MAX(ORDER_DATE) ORDER_DATE , NVL(MAX(REMARK_SELLER), '''') REMARK_SELLER, NVL(MAX(REMARK_BUYER), '''') REMARK_BUYER FROM (    SELECT ORDER_ID, PRODUCT_NAME, A.PRODUCT_ID, D.PRODUCT_CODE, PROVIDER_NAME, E.ID_UNIT ID_UNIT    , CASE WHEN A.STATUS_ID IN (''E'',''F'',''P'',''S'',''O'',''D'') THEN ''ABIERTO''        ELSE ''CERRADO'' END SITUACION    , TOTAL_AMOUNT    , TAX_AMOUNT    , DISCOUNT_AMOUNT    , (PRODUCT_PRICE - (DISCOUNT_AMOUNT/QUANTITY)) PRODUCT_PRICE_FINAL    , QUANTITY,  NEW_QUANTITY, NEW_PRODUCT_PRICE_FINAL, BAN_OFICIAL_PRICE, TAX_APPLY, C.STATUS_ID, C.STATUS_NAME, C.BAN_PRICE, C.BAN_QUANTITY, PRODUCT_PRICE    , (QUANTITY * PRODUCT_PRICE) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX     , ((QUANTITY * PRODUCT_PRICE) + DISCOUNT_AMOUNT) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, ORDER_DATE    , REMARK_SELLER, REMARK_BUYER     FROM KRC_PURCHASE A, KRC_TAX_TYPE B,        (SELECT           KRC_STATUS.STATUS_OBJECT_ID STATUS_ID, KRC_STATUS.STATUS_NAME           , MAX(KRC_STATUS.BAN_PRICE) BAN_PRICE, MAX(KRC_STATUS.BAN_QUANTITY) BAN_QUANTITY         FROM KRC_STATUS, KRR_USER_ROLE, KRC_ROLE         WHERE KRR_USER_ROLE.USER_ID = $3 AND KRR_USER_ROLE.ROLE_ID = KRC_ROLE.ROLE_ID           AND KRC_ROLE.ROLE_NAME = KRC_STATUS.ROLE         GROUP BY KRC_STATUS.STATUS_OBJECT_ID, KRC_STATUS.STATUS_NAME        ) C,         (SELECT PRODUCT_ID, PRODUCT_CODE, UNIT_ID FROM KRC_PRODUCT) D,        (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) E     WHERE ORDER_ID = $1 AND PROVIDER_NAME = $2       AND A.TAX_ID=B.TAX_ID AND A.STATUS_ID=C.STATUS_ID AND A.PRODUCT_ID = D.PRODUCT_ID AND D.UNIT_ID = E.CVE_UNIT     ) AA GROUP BY ORDER_ID, PROVIDER_NAME, PRODUCT_ID, TAX_APPLY, STATUS_NAME;',
    'Líneas de compra por order_id',
    'SELECT líneas de la compra filtradas por ORDER_ID + PROVIDER_NAME + USER_ID',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Detalle de compra'
);

-- GTSTPRCH → queryGetStatusPurchase()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTSTPRCH',
    'SELECT   ORDER_ID, PROVIDER_NAME  ,CASE WHEN COUNT(DISTINCT STATUS_NAME)=1 THEN max(STATUS_NAME)  ELSE ''VARIOS'' END ALL_STATUS  , CASE WHEN COUNT(DISTINCT STATUS_ID)=1 THEN max(STATUS_ID)		ELSE ''VARIOS'' END STATUS_ID  , COUNT(DISTINCT STATUS_NAME) NUM_STATUS FROM (   SELECT A.ORDER_ID, A.PROVIDER_NAME, C.STATUS_ID, C.STATUS_NAME   FROM KRC_PURCHASE A,		(SELECT STATUS_OBJECT_ID STATUS_ID, STATUS_NAME         FROM KRC_STATUS         GROUP BY STATUS_OBJECT_ID, STATUS_NAME) C    WHERE A.ORDER_ID = $1 AND A.PROVIDER_NAME = $2     AND A.STATUS_ID=C.STATUS_ID) AA GROUP BY ORDER_ID, PROVIDER_NAME;',
    'Estado consolidado de compra',
    'Devuelve el ALL_STATUS resumido de una compra',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Cabecera detalle compra'
);

-- UPDPRCHST → queryUpdatePurchaseState()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'UPDPRCHST',
    'UPDATE KRC_PURCHASE SET STATUS_ID = $1, USER_MODIFY_ID = $2, MODIFY_DATE = $3 WHERE ORDER_ID = $4 AND PROVIDER_NAME= $5;',
    'Cambiar estado de cabecera de compra',
    'UPDATE STATUS_ID en KRC_PURCHASE para una compra completa',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Acciones de compra'
);

-- UPDPLNST → queryUpdatePurchaseLineState()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'UPDPLNST',
    'UPDATE KRC_PURCHASE SET STATUS_ID = $1, USER_MODIFY_ID = $2, MODIFY_DATE = $3 WHERE ORDER_ID = $4 AND PROVIDER_NAME= $5 and PRODUCT_ID = $6;',
    'Cambiar estado de línea de compra',
    'UPDATE STATUS_ID en KRC_PURCHASE para una línea concreta',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Acciones de línea'
);

-- UPDPL1B → queryUpdatePurchaseLine(1, 'BUYER')
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'UPDPL1B',
    'UPDATE KRC_PURCHASE SET NEW_QUANTITY = $1, NEW_PRODUCT_PRICE_FINAL = $2, BAN_OFICIAL_PRICE = $3, TOTAL_BEFORE_DISCOUNT = $4, TOTAL_AMOUNT = $5, DISCOUNT_AMOUNT = $6, TAX_AMOUNT = $7, USER_MODIFY_ID = $8, MODIFY_DATE = $9, STATUS_ID = ''O'', REMARK_BUYER = $10 WHERE ORDER_ID = $11 AND PROVIDER_NAME= $12 AND PRODUCT_ID = $13;',
    'Modificar línea: precio+cantidad (BUYER)',
    'UPDATE precio y cantidad por el comprador, escribe en REMARK_BUYER',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Edición de línea por comprador'
);

-- UPDPL1S → queryUpdatePurchaseLine(1, 'SELLER')
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'UPDPL1S',
    'UPDATE KRC_PURCHASE SET NEW_QUANTITY = $1, NEW_PRODUCT_PRICE_FINAL = $2, BAN_OFICIAL_PRICE = $3, TOTAL_BEFORE_DISCOUNT = $4, TOTAL_AMOUNT = $5, DISCOUNT_AMOUNT = $6, TAX_AMOUNT = $7, USER_MODIFY_ID = $8, MODIFY_DATE = $9, STATUS_ID = ''O'', REMARK_SELLER = $10 WHERE ORDER_ID = $11 AND PROVIDER_NAME= $12 AND PRODUCT_ID = $13;',
    'Modificar línea: precio+cantidad (SELLER)',
    'UPDATE precio y cantidad por el vendedor, escribe en REMARK_SELLER',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Edición de línea por vendedor'
);

-- UPDPL2B → queryUpdatePurchaseLine(2, 'BUYER')
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'UPDPL2B',
    'UPDATE KRC_PURCHASE SET NEW_PRODUCT_PRICE_FINAL = $1, BAN_OFICIAL_PRICE = $2, TOTAL_BEFORE_DISCOUNT = $3, TOTAL_AMOUNT = $4, DISCOUNT_AMOUNT = $5, TAX_AMOUNT = $6, USER_MODIFY_ID = $7, MODIFY_DATE = $8, STATUS_ID = ''O'', REMARK_BUYER = $9 WHERE ORDER_ID = $10 AND PROVIDER_NAME= $11 AND PRODUCT_ID = $12;',
    'Modificar línea: solo precio (BUYER)',
    'UPDATE solo precio por el comprador',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Edición de línea por comprador'
);

-- UPDPL2S → queryUpdatePurchaseLine(2, 'SELLER')
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'UPDPL2S',
    'UPDATE KRC_PURCHASE SET NEW_PRODUCT_PRICE_FINAL = $1, BAN_OFICIAL_PRICE = $2, TOTAL_BEFORE_DISCOUNT = $3, TOTAL_AMOUNT = $4, DISCOUNT_AMOUNT = $5, TAX_AMOUNT = $6, USER_MODIFY_ID = $7, MODIFY_DATE = $8, STATUS_ID = ''O'', REMARK_SELLER = $9 WHERE ORDER_ID = $10 AND PROVIDER_NAME= $11 AND PRODUCT_ID = $12;',
    'Modificar línea: solo precio (SELLER)',
    'UPDATE solo precio por el vendedor',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Edición de línea por vendedor'
);

-- UPDPL3B → queryUpdatePurchaseLine(3, 'BUYER')
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'UPDPL3B',
    'UPDATE KRC_PURCHASE SET NEW_QUANTITY = $1, TOTAL_BEFORE_DISCOUNT = $2, TOTAL_AMOUNT = $3, DISCOUNT_AMOUNT = $4, TAX_AMOUNT = $5, USER_MODIFY_ID = $6, MODIFY_DATE = $7, STATUS_ID = ''O'', REMARK_BUYER = $8 WHERE ORDER_ID = $9 AND PROVIDER_NAME= $10 AND PRODUCT_ID = $11;',
    'Modificar línea: solo cantidad (BUYER)',
    'UPDATE solo cantidad por el comprador',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Edición de línea por comprador'
);

-- UPDPL3S → queryUpdatePurchaseLine(3, 'SELLER')
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'UPDPL3S',
    'UPDATE KRC_PURCHASE SET NEW_QUANTITY = $1, TOTAL_BEFORE_DISCOUNT = $2, TOTAL_AMOUNT = $3, DISCOUNT_AMOUNT = $4, TAX_AMOUNT = $5, USER_MODIFY_ID = $6, MODIFY_DATE = $7, STATUS_ID = ''O'', REMARK_SELLER = $8 WHERE ORDER_ID = $9 AND PROVIDER_NAME= $10 AND PRODUCT_ID = $11;',
    'Modificar línea: solo cantidad (SELLER)',
    'UPDATE solo cantidad por el vendedor',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Edición de línea por vendedor'
);

-- STTRNSTO → getStatusToTransitionTo()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'STTRNSTO',
    'SELECT A.DESTINATION_STATUS_ID, D.STATUS_NAME, D.BAN_PRICE, D.BAN_QUANTITY, A.PRIORITY, C.ROLE_NAME FROM  KRC_STATUS_FLOW A, KRR_USER_ROLE B, KRC_ROLE C, KRC_STATUS D WHERE   B.USER_ID = $2  AND B.STATUS_ID = ''A''  AND B.ROLE_ID = C.ROLE_ID  AND A.ROLE = C.ROLE_NAME  AND A.ORIGIN_STATUS_ID = $1  AND A.STATUS_ID = ''A''  AND A.STATUS_OBJECT = ''P''  AND D.STATUS_ID = ''A''  AND D.STATUS_OBJECT = ''P''  AND D.ROLE = C.ROLE_NAME  AND A.DESTINATION_STATUS_ID = D.STATUS_OBJECT_ID ORDER BY A.PRIORITY',
    'Estados destino permitidos',
    'Lista DESTINATION_STATUS_ID a los que el usuario puede transicionar la compra',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Botones de acción'
);

-- GTBANPRQT → getBanPriceUndBanQuantityValues()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTBANPRQT',
    'SELECT KRC_STATUS.STATUS_OBJECT_ID DESTINATION_STATUS_ID, KRC_STATUS.STATUS_NAME , KRC_STATUS.BAN_PRICE BAN_PRICE, KRC_STATUS.BAN_QUANTITY BAN_QUANTITY, 1 PRIORITY, KRC_STATUS.ROLE ROLE_NAME FROM KRC_STATUS, KRR_USER_ROLE, KRC_ROLE WHERE KRR_USER_ROLE.USER_ID = $1 AND KRR_USER_ROLE.ROLE_ID = KRC_ROLE.ROLE_ID AND KRC_ROLE.ROLE_NAME = KRC_STATUS.ROLE AND KRC_STATUS.STATUS_OBJECT_ID = $2 LIMIT 1;',
    'BAN_PRICE / BAN_QUANTITY de un estado',
    'SELECT flags de bloqueo de precio/cantidad para un estado destino',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Edición de línea'
);

-- INSPRCH → queryInsertPurchased()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'INSPRCH',
    'INSERT INTO KRC_PURCHASE( ORDER_ID , INVOICE_ID, PROVIDER_NAME, PRODUCT_NAME, PRODUCT_ID, QUANTITY, PRODUCT_PRICE, TOTAL_BEFORE_DISCOUNT, TOTAL_AMOUNT, OPEN_AMOUNT, DISCOUNT_AMOUNT, TAX_ID, TAX_AMOUNT, ORDER_DATE, PRODUCT_ENTRY_DATE, CLOSE_DATE, STATUS_DATE, MODIFY_DATE, STATUS_ID, USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, PARTNER_NAME, PAYMENT_METHOD, ADDR_ID, CONTACT_ID, CONTACT_NAME, CONTACT_POSITION, CONTACT_PHONE, EMAIL, DELIVERY_DATE, DISCOUNT_TYPE) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, sysdate(), sysdate(), sysdate(), sysdate(), sysdate(), ''E'', $14, null, ''APP'', $15, $16, '''', 0, 0, '''', null, '''', '''', sysdate(), ''PCT'');',
    'Insertar línea de compra',
    'INSERT en KRC_PURCHASE (línea de compra inicial)',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Confirmar compra'
);

-- GTDFLOGAD → getDefaultLogisticAddress()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTDFLOGAD',
    'SELECT
    ADDR.ADDR_ID
    , ADDR.ADDR_STREET
    , ADDR.ADDR_NUMBER
    , ADDR.ADDR_COMPLEMENT
    , ADDR.SUBURB
    , ADDR.DISTRICT
    , ADDR.CITY
    , ADDR.PROVINCE
    , ADDR.STATE
    , ADDR.COUNTRY
    , ADDR.ADDR_ZIP_CODE
    , ADDR.INDICATION
    , ADDR.STATUS_ID
    FROM KRC_ADDRESS ADDR
    INNER JOIN KRC_PERSONE_IDENTITY PER
    ON (ADDR.ADDR_OBJECT = PER.PERSONE_ID AND ADDR.ADDR_TYPE = ''L'' AND ADDR.STATUS_ID = ''D'')
    INNER JOIN  KRC_USER USER
    ON (PER.USER_ID = USER.USER_ID)
    WHERE USER.USER_ID = $1;',
    'Dirección logística por defecto del usuario',
    'SELECT KRC_ADDRESS con ADDR_TYPE=L y STATUS_ID=D (default)',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Pantalla de dirección'
);

-- GTROLEUSR → getRoleByUser()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTROLEUSR',
    'SELECT C.ROLE_NAME ROLE_NAME FROM KRC_USER A, KRR_USER_ROLE B, KRC_ROLE C WHERE A.USER_ID = B.USER_ID AND B.ROLE_ID = C.ROLE_ID AND A.USER_ID = $1;',
    'Rol del usuario',
    'SELECT ROLE_NAME en KRR_USER_ROLE para un USER_ID',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Autorización'
);

-- GTADDRS → getAdresses()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTADDRS',
    'SELECT
    ADDR.ADDR_ID
    , ADDR.ADDR_STREET
    , ADDR.ADDR_NUMBER
    , ADDR.ADDR_COMPLEMENT
    , ADDR.SUBURB
    , ADDR.DISTRICT
    , ADDR.CITY
    , ADDR.PROVINCE
    , ADDR.STATE
    , ADDR.COUNTRY
    , ADDR.ADDR_ZIP_CODE
    , ADDR.INDICATION
    , ADDR.STATUS_ID
    FROM KRC_ADDRESS ADDR
    INNER JOIN KRC_PERSONE_IDENTITY PER
    ON (ADDR.ADDR_OBJECT = PER.PERSONE_ID AND ADDR.ADDR_TYPE = ''L'')
    WHERE PER.PERSONE_ID = $1;',
    'Direcciones logísticas de un PERSONE_ID',
    'SELECT de todas las direcciones logísticas de la persona',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Gestión de direcciones'
);

-- GTTAXTYPE → getTaxType()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTTAXTYPE',
    'SELECT
    TAX_TYPE
    FROM
    KRRI.KRC_TAX_TYPE
    WHERE TAX_COUNTRY = ''ESP'' ORDER BY TAX_ID;',
    'Tipos de impuesto (ESP)',
    'SELECT TAX_TYPE de KRC_TAX_TYPE para España',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Alta de producto'
);

-- GTUNITTYP → getUnitType()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTUNITTYP',
    'SELECT
    ID_UNIT
    FROM
    KRRI.DMD_UNIT
    WHERE CVE_UNIT > 0 ORDER BY CVE_UNIT;',
    'Unidades de medida',
    'SELECT ID_UNIT de DMD_UNIT (CVE_UNIT > 0)',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Alta de producto'
);

-- GTPROVID → getProviders()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPROVID',
    'SELECT
    PERSONE_NAME
    FROM KRRI.KRC_PERSONE_IDENTITY
    WHERE STATUS_ID = ''A'' AND PERSONE_TYPE = ''P''
    ORDER BY PERSONE_NAME;',
    'Proveedores activos',
    'SELECT proveedores activos (PERSONE_TYPE=P)',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Alta de producto'
);

-- GTPRTNRS → getPartners()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRTNRS',
    'SELECT
    PERSONE_NAME
    FROM KRRI.KRC_PERSONE_IDENTITY
    WHERE STATUS_ID = ''A'' AND PERSONE_TYPE = ''R''
    ORDER BY PERSONE_NAME;',
    'Partners activos',
    'SELECT partners activos (PERSONE_TYPE=R)',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Alta de producto'
);

-- GTPRODTYP → getProductTypes()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRODTYP',
    'SELECT
    PRODUCT_TYPE
    FROM KRRI.KRC_PRODUCT_TYPE
    WHERE STATUS_ID = ''A''
    AND PARTNER_ID = $1;',
    'Tipos de producto del partner',
    'SELECT PRODUCT_TYPE filtrado por PARTNER_ID = $1',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Alta de producto'
);

-- INSPROD → queryInsertNewProduct()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'INSPROD',
    'INSERT INTO KRRI.KRC_PRODUCT
    (
        PRODUCT_ID
        , PRODUCT_CODE
        , PRODUCT_CATEGORY_ID
        , PRODUCT_NAME
        , PRODUCT_NAME_INTERNAL
        , MIN_QUANTITY_SELL
        , LANGUAGE_CODE
        , PRODUCT_PRICE
        , PRODUCT_PRICE_FINAL
        , DISCOUNT_VALUE
        , DISCOUNT_TYPE
        , TAX_ID
        , CURRENCY_ID
        , UNIT_ID
        , WEEKS_WARNING
        , QUANTITY_MIN_PRICE
        , QUANTITY_MAX_PRICE
        , PRODUCT_TYPE_ID
        , PROVIDER_ID
        , PARTNER_ID
        , PARTNER_NAME
        , STATUS_ID
        , CREATE_DATE
        , EFF_DATE
        , EXP_DATE
        , STATUS_DATE
        , USER_CREATE_ID
        , SCENARIO
        , COUNTABLE_FLAG
        , SOURCE_ID
    )VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, sysdate(), sysdate(), sysdate(), sysdate(), $27, ''APP'', (SELECT BAN_INVENTORY FROM KRRI.KRC_PRODUCT_TYPE WHERE PRODUCT_TYPE_ID = $18), ''APP'');',
    'Insertar nuevo producto',
    'INSERT en KRC_PRODUCT con todos los campos',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Alta de producto'
);

-- GTPRODSEQ → queryNewProductSequence()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTPRODSEQ',
    'select KRRI.nextval(''SEQ_PRODUCT'') PRODUCT_ID, CAST(date_format(CONVERT_TZ( sysdate(), ''UTC'', ''Europe/Paris''),''%Y%m%d'') AS UNSIGNED) CURRENT_DAY;',
    'Siguiente valor de SEQ_PRODUCT',
    'Devuelve nextval de SEQ_PRODUCT y la fecha actual',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Crear nuevo producto'
);

-- GTSHIFTS → getShifts()
INSERT INTO KRC_QUERY (
    QUERY_CODE, QUERY, NAME, DESCRIPTION, STATUS_ID,
    CREATE_DATE, EFF_DATE, EXP_DATE, MODIFY_DATE, STATUS_DATE,
    USER_CREATE_ID, USER_MODIFY_ID, SCENARIO, PARTNER_ID, UNIT, FUNCTIONALITY
) VALUES (
    'GTSHIFTS',
    'SELECT
    SHIFT_ID
    , SHIFT_HOUR_START
    , SHIFT_HOUR_END
    , DAY_TYPE
    , USER_CREATE_ID
    , PARTNER_ID
    , PARTNER_NAME
    FROM KRRI.KRC_SHIFT
    WHERE STATUS_ID = ''A''
    AND PARTNER_ID = $1;',
    'Turnos del partner',
    'SELECT SHIFT_ID de KRC_SHIFT filtrado por PARTNER_ID = $1',
    'A',
    NOW(), CURRENT_DATE(), NULL, NULL, CURRENT_DATE(),
    1, NULL, 'K', 0, 'APP', 'Configuración partner'
);

-- ===== Validación =====
SELECT COUNT(*) AS k_count FROM KRC_QUERY WHERE SCENARIO = 'K';

-- Si k_count = 32 → ejecutar:  COMMIT;
-- Si k_count != 32 → ejecutar: ROLLBACK;