//
// Return all the product, which are in the table KRC_PRODUCTS
// plus all their JOINS
//
export function getProducts (): string {
    const query = 
    `SELECT
        PROD.PRODUCT_ID
        , PROD.PRODUCT_CODE
        , PROD.PRODUCT_CATEGORY_ID
        , CAT.PRODUCT_CATEGORY
        , PROD.PRODUCT_NAME
        , PROD.PRODUCT_NAME_INTERNAL
        , PROD.PRODUCT_DESCRIPTION
        , PROD.BRAND_ID
        , BRAND.BRAND
        , PROD.MIN_QUANTITY_SELL
        , PROD.LANGUAGE_CODE
        , PROD.PRODUCT_PRICE/10000 PRODUCT_PRICE
        , PROD.TAX_ID
        , PROD.CURRENCY_ID
        , PROD.UNIT_ID
        , DMD_UNIT.DES_UNIT
        , PROD.WEEKS_WARNING
        , PROD.QUANTITY_MIN_PRICE
        , PROD.QUANTITY_MAX_PRICE
        , PROD.TYPE_DAY_DELIVERY
        , DMD_DELIVERY_TYPE.DES_DELIVERY_TYPE
        , PROD.MIN_DAYS_DELIVERY
        , PROD.MAX_DAYS_DELIVERY
        , PROD.REMARK
        , PROD.DAYS_DELIVERY
        , PROD.PRODUCT_TYPE_ID
        , PROD.PROVIDER_ID
        , PERSONE.PERSONE_NAME
        , PROD.PARTNER_ID
        , PARTNER.PERSONE_NAME PARTNER_NAME
        , PROD.EFF_DATE
        , PROD.EXP_DATE
        , PROD.DAYS_EXP
        , PROD.EXPOILED_FLAG
        , PROD.COUNTABLE_FLAG
        , PROD.SOURCE_ID
        , PROD.NUM_IMAGES
        , PROD.NUM_VIDEOS
    FROM
        KRC_PRODUCT PROD
        LEFT JOIN KRC_PRODUCT_CATEGORY CAT
        ON (CAT.PRODUCT_CATEGORY_ID = PROD.PRODUCT_CATEGORY_ID AND CAT.STATUS_ID = 'A' )
        LEFT OUTER JOIN KRC_BRAND BRAND
        ON (BRAND.BRAND_ID = PROD.BRAND_ID AND BRAND.STATUS_ID = 'A')
        LEFT OUTER JOIN KRC_TAX_TYPE TAX
        ON (TAX.TAX_ID = PROD.TAX_ID)
        LEFT OUTER JOIN DMD_UNIT
        ON (DMD_UNIT.CVE_UNIT = PROD.UNIT_ID)
        LEFT OUTER JOIN DMD_DELIVERY_TYPE
        ON (PROD.TYPE_DAY_DELIVERY = DMD_DELIVERY_TYPE.CVE_DELIVERY_TYPE)
        LEFT OUTER JOIN KRC_PRODUCT_TYPE PRODUCT_TYPE
        ON (PROD.PRODUCT_TYPE_ID = PRODUCT_TYPE.PRODUCT_TYPE_ID)
        LEFT OUTER JOIN KRC_PERSONE_IDENTITY PERSONE
        ON (PROD.PROVIDER_ID = PERSONE.PERSONE_ID AND PERSONE.STATUS_ID = 'A')
        LEFT OUTER JOIN KRC_PERSONE_IDENTITY PARTNER
        ON (PROD.PARTNER_ID = PARTNER.PERSONE_ID AND PARTNER.STATUS_ID = 'A')
    WHERE
        PROD.STATUS_ID = 'A' and PROD.PRODUCT_ID <= 10
    ;`;
    return query;
}
export function getProductsWithTags(): string {
    const query =
    `SELECT PRODUCT.PRODUCT_ID, PRODUCT.PRODUCT_CODE, PRODUCT.PRODUCT_CATEGORY_ID
    , PRODUCT.PRODUCT_CATEGORY, PRODUCT.PRODUCT_NAME, PRODUCT.PRODUCT_NAME_INTERNAL
    , PRODUCT.PRODUCT_DESCRIPTION, PRODUCT.BRAND_ID, PRODUCT.BRAND, PRODUCT.MIN_QUANTITY_SELL
    , PRODUCT.LANGUAGE_CODE, PRODUCT.PRODUCT_PRICE, PRODUCT.TAX_ID, PRODUCT.CURRENCY_ID
    , PRODUCT.UNIT_ID, PRODUCT.DES_UNIT, PRODUCT.WEEKS_WARNING, PRODUCT.QUANTITY_MIN_PRICE
    , PRODUCT.QUANTITY_MAX_PRICE, PRODUCT.TYPE_DAY_DELIVERY, PRODUCT.DES_DELIVERY_TYPE
    , PRODUCT.MIN_DAYS_DELIVERY, PRODUCT.MAX_DAYS_DELIVERY, PRODUCT.REMARK
    , PRODUCT.DAYS_DELIVERY, PRODUCT.PRODUCT_TYPE_ID, PRODUCT.PROVIDER_ID
    , PRODUCT.PERSONE_NAME, PRODUCT.PARTNER_ID, PRODUCT.PARTNER_NAME, PRODUCT.EFF_DATE
    , PRODUCT.EXP_DATE, PRODUCT.DAYS_EXP, PRODUCT.EXPOILED_FLAG, PRODUCT.COUNTABLE_FLAG
    , PRODUCT.SOURCE_ID, PRODUCT.NUM_IMAGES, PRODUCT.NUM_VIDEOS
    FROM
    (
        SELECT
            PROD.PRODUCT_ID
            , PROD.PRODUCT_CODE
            , PROD.PRODUCT_CATEGORY_ID
            , CAT.PRODUCT_CATEGORY
            , PROD.PRODUCT_NAME
            , PROD.PRODUCT_NAME_INTERNAL
            , PROD.PRODUCT_DESCRIPTION
            , PROD.BRAND_ID
            , BRAND.BRAND
            , PROD.MIN_QUANTITY_SELL
            , PROD.LANGUAGE_CODE
            , PROD.PRODUCT_PRICE
            , PROD.TAX_ID
            , PROD.CURRENCY_ID
            , PROD.UNIT_ID
            , DMD_UNIT.DES_UNIT
            , PROD.WEEKS_WARNING
            , PROD.QUANTITY_MIN_PRICE
            , PROD.QUANTITY_MAX_PRICE
            , PROD.TYPE_DAY_DELIVERY
            , DMD_DELIVERY_TYPE.DES_DELIVERY_TYPE
            , PROD.MIN_DAYS_DELIVERY
            , PROD.MAX_DAYS_DELIVERY
            , PROD.REMARK
            , PROD.DAYS_DELIVERY
            , PROD.PRODUCT_TYPE_ID
            , PROD.PROVIDER_ID
            , PERSONE.PERSONE_NAME
            , PROD.PARTNER_ID
            , PARTNER.PERSONE_NAME PARTNER_NAME
            , PROD.EFF_DATE
            , PROD.EXP_DATE
            , PROD.DAYS_EXP
            , PROD.EXPOILED_FLAG
            , PROD.COUNTABLE_FLAG
            , PROD.SOURCE_ID
            , PROD.NUM_IMAGES
            , PROD.NUM_VIDEOS
        FROM
            KRC_PRODUCT PROD
            LEFT JOIN KRC_PRODUCT_CATEGORY CAT
            ON (CAT.PRODUCT_CATEGORY_ID = PROD.PRODUCT_CATEGORY_ID AND CAT.STATUS_ID = 'A' )
            LEFT OUTER JOIN KRC_BRAND BRAND
            ON (BRAND.BRAND_ID = PROD.BRAND_ID AND BRAND.STATUS_ID = 'A')
            LEFT OUTER JOIN KRC_TAX_TYPE TAX
            ON (TAX.TAX_ID = PROD.TAX_ID)
            LEFT OUTER JOIN DMD_UNIT
            ON (DMD_UNIT.CVE_UNIT = PROD.UNIT_ID)
            LEFT OUTER JOIN DMD_DELIVERY_TYPE
            ON (PROD.TYPE_DAY_DELIVERY = DMD_DELIVERY_TYPE.CVE_DELIVERY_TYPE)
            LEFT OUTER JOIN KRC_PRODUCT_TYPE PRODUCT_TYPE
            ON (PROD.PRODUCT_TYPE_ID = PRODUCT_TYPE.PRODUCT_TYPE_ID)
            LEFT OUTER JOIN KRC_PERSONE_IDENTITY PERSONE
            ON (PROD.PROVIDER_ID = PERSONE.PERSONE_ID AND PERSONE.STATUS_ID = 'A')
            LEFT OUTER JOIN KRC_PERSONE_IDENTITY PARTNER
            ON (PROD.PARTNER_ID = PARTNER.PERSONE_ID AND PARTNER.STATUS_ID = 'A' and PARTNER.PERSONE_TYPE = 'P')
        WHERE
            PROD.STATUS_ID = 'A'
    ) PRODUCT
    INNER JOIN 
    (
      SELECT PERSONE_ID, PERSONE_NAME
      FROM KRC_PERSONE_IDENTITY
      WHERE PERSONE_TYPE='P' AND STATUS_ID='A' 
    ) PERSONE
    ON (PRODUCT.PROVIDER_ID = PERSONE.PERSONE_ID)
    INNER JOIN
    (
      SELECT PRODUCT_CATEGORY_ID, TAG 
      FROM KRC_PRODUCT_TAGS
      WHERE STATUS_ID='A'
        GROUP BY PRODUCT_CATEGORY_ID, TAG
    ) TAG
    ON (TAG.PRODUCT_CATEGORY_ID=PRODUCT.PRODUCT_CATEGORY_ID)
    ;
    `;
    return query;
}
//
// Return all the products, which are in the table KRC_PRODUCT_AVAIL
// 
export function queryGetProductsAvailable (): string {
    const query = "SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, BRAND, NUM_IMAGES, NUM_VIDEOS" +
    ", AVAIL, PRODUCT_PRICE, PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL, TAX_ID, TAX_APPLY" +
    ", case when ID_UNIT = 'LT' then 'Lt'" +
    "    when ID_UNIT = 'UNI' then 'Ud'" +
    "    when ID_UNIT = 'KG' then 'Kg'" +  
    "  end AS ID_UNIT" +
    ", REMARK, MIN_QUANTITY_SELL " +
    "FROM (" +
    "select A.PRODUCT_ID, C.PRODUCT_NAME, C.PRODUCT_DESCRIPTION, D.PRODUCT_TYPE, C.BRAND, C.NUM_IMAGES, C.NUM_VIDEOS" +
	", ROUND(SUM(QUANTITY)) AVAIL, ROUND(max(PRODUCT_PRICE/10000), 2) PRODUCT_PRICE" +
    ", E.PERSONE_ID, E.PERSONE_NAME, E.BUSINESS_NAME, E.EMAIL, C.TAX_ID, F.TAX_APPLY" +
	", TIP_UNIDAD.ID_UNIT, C.REMARK, C.MIN_QUANTITY_SELL " +
    ", ROW_NUMBER() OVER (PARTITION BY C.PRODUCT_CATEGORY_ID, E.PERSONE_NAME ORDER BY IFNULL(C.MODIFY_DATE, C.CREATE_DATE) DESC) AS RN " +
	"FROM (" +
	"        SELECT PRODUCT_AVAIL_ID,ORDER_ID,PRODUCT_ID,QUANTITY,PRODUCT_PRICE,PRODUCT_PRICE_PAID,PREDICTABLE_FINISH_DATE," +
	"        RESET_MANUAL_DATE,CALIBRATE_DATE,CREATE_DATE,EXP_DATE,MODIFY_DATE,STATUS_DATE,USER_CREATE_ID,USER_MODIFY_ID," +
	"        METHOD,PRODUCT_CATEGORY_ID,PARTNER_ID,PARTNER_NAME " +
	"        FROM KRC_PRODUCT_AVAIL" +
	"     ) A " +
	"INNER JOIN (" +
    "  SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE_ID, BRAND, REMARK, NUM_IMAGES" +
    ", NUM_VIDEOS, PROVIDER_ID, TAX_ID" +
	", UNIT_ID, PRODUCT_CATEGORY_ID, IFNULL(MIN_QUANTITY_SELL, 1) AS MIN_QUANTITY_SELL, MODIFY_DATE, CREATE_DATE " +
    "FROM KRC_PRODUCT " +
    "WHERE STATUS_ID='A' GROUP BY PRODUCT_ID) C " +
	"ON (A.PRODUCT_ID = C.PRODUCT_ID) " +
	"LEFT OUTER JOIN (SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE FROM KRC_PRODUCT_TYPE WHERE STATUS_ID = 'A') D " +
	"ON (C.PRODUCT_TYPE_ID = D.PRODUCT_TYPE_ID) " +
    "LEFT OUTER JOIN (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) TIP_UNIDAD " +
    "ON (C.UNIT_ID = TIP_UNIDAD.CVE_UNIT) " +
    "LEFT OUTER JOIN (SELECT PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL FROM KRC_PERSONE_IDENTITY " +
    "WHERE STATUS_ID = 'A' AND PERSONE_TYPE = 'P') E " +
    "ON (C.PROVIDER_ID = E.PERSONE_ID) " +
    "LEFT OUTER JOIN (SELECT TAX_ID, TAX_APPLY FROM KRC_TAX_TYPE) F " +
    "ON (C.TAX_ID = F.TAX_ID) " +
	" WHERE A.QUANTITY>0 " +
	"GROUP BY A.PRODUCT_ID, PRODUCT_NAME " +
	"ORDER BY PRODUCT_NAME" +
	") AA WHERE AA.RN=1;";
	return query;
}
export function queryGetProductsAvailableWithPartnerId (): string {
    const query = "SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE, BRAND, NUM_IMAGES, NUM_VIDEOS" +
    ", PRODUCT_PRICE, ROUND(PRODUCT_PRICE*(1+TAX_APPLY/100),2) TOTAL_BEFORE_DISCOUNT, ROUND(PRODUCT_PRICE_DISCOUNTED*(TAX_APPLY/100),2) TAX_AMOUNT" +
    ", PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL, TAX_ID, TAX_APPLY" +
    ", PRODUCT_PRICE_DISCOUNTED, ROUND(PRODUCT_PRICE_DISCOUNTED*(1+TAX_APPLY/100),2) TOTAL_AMOUNT " +
    ", (PRODUCT_PRICE-PRODUCT_PRICE_DISCOUNTED) DISCOUNT_AMOUNT" +
    ", case when ID_UNIT = 'LT' then 'Lt'" +
    "    when ID_UNIT = 'UNI' then 'Ud'" +
    "    when ID_UNIT = 'KG' then 'Kg'" +  
    "  end AS ID_UNIT" +
    ", REMARK, MIN_QUANTITY_SELL, PARTNER_ID, PARTNER_NAME, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE, PRODUCT_CATEGORY_ID, RN " +
    "FROM (" +
    "select A.PRODUCT_ID, A.PRODUCT_CODE, A.PRODUCT_NAME, A.PRODUCT_DESCRIPTION, D.PRODUCT_TYPE, A.BRAND, A.NUM_IMAGES, A.NUM_VIDEOS" +
	", A.PRODUCT_PRICE PRODUCT_PRICE, A.PRODUCT_PRICE_FINAL PRODUCT_PRICE_DISCOUNTED" +
    ", E.PERSONE_ID, E.PERSONE_NAME, E.BUSINESS_NAME, E.EMAIL, A.TAX_ID, F.TAX_APPLY" +
	", TIP_UNIDAD.ID_UNIT, A.REMARK, A.MIN_QUANTITY_SELL, A.PRODUCT_NAME_LONG, A.PARTNER_ID, A.PARTNER_NAME " +
    ", A.MODIFY_DATE, A.CREATE_DATE , A.QUANTITY_MIN_PRICE,  A.QUANTITY_MAX_PRICE, A.PRODUCT_CATEGORY_ID" +
    ", ROW_NUMBER() OVER (PARTITION BY A.PRODUCT_NAME, E.PERSONE_NAME ORDER BY A.PARTNER_ID DESC, IFNULL(A.MODIFY_DATE, A.CREATE_DATE) DESC, A.PRODUCT_PRICE_FINAL DESC, A.PRODUCT_ID DESC) AS RN " +
	"FROM (" +
	"        SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME_INTERNAL PRODUCT_NAME, PRODUCT_NAME PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE_ID, BRAND, REMARK, NUM_IMAGES" +
	"        , NUM_VIDEOS, PROVIDER_ID, TAX_ID, PRODUCT_PRICE , PRODUCT_PRICE_FINAL, PARTNER_ID, PARTNER_NAME" +
	"        , UNIT_ID, PRODUCT_CATEGORY_ID, IFNULL(MIN_QUANTITY_SELL, 1) AS MIN_QUANTITY_SELL " +
    "        , MODIFY_DATE, CREATE_DATE, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE" +
	"        FROM KRC_PRODUCT" +
	"        WHERE STATUS_ID='A' AND PARTNER_ID IN (1, $1)" +
    "   ) A " +
	"LEFT OUTER JOIN (SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE FROM KRC_PRODUCT_TYPE WHERE STATUS_ID = 'A') D " +
	"ON (A.PRODUCT_TYPE_ID = D.PRODUCT_TYPE_ID) " +
    "LEFT OUTER JOIN (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) TIP_UNIDAD " +
    "ON (A.UNIT_ID = TIP_UNIDAD.CVE_UNIT) " +
    "LEFT OUTER JOIN (SELECT PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL FROM KRC_PERSONE_IDENTITY " +
    "WHERE STATUS_ID = 'A' AND PERSONE_TYPE = 'P') E " +
    "ON (A.PROVIDER_ID = E.PERSONE_ID) " +
    "LEFT OUTER JOIN (SELECT TAX_ID, TAX_APPLY FROM KRC_TAX_TYPE) F " +
    "ON (A.TAX_ID = F.TAX_ID) " +
	"ORDER BY PRODUCT_NAME" +
	") AA " +
    "WHERE (CASE WHEN $1 < 10000 THEN PARTNER_ID IN (1,$1) ELSE PARTNER_ID IN ($1) END ) " +
    "ORDER BY PRODUCT_CATEGORY_ID, PERSONE_NAME, PARTNER_ID DESC, RN;";
	return query;
}

export function queryGetProductsAvailableWithOutPartnerId (): string {
    const query = "SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE, BRAND, NUM_IMAGES, NUM_VIDEOS" +
    ", PRODUCT_PRICE, ROUND(PRODUCT_PRICE*(1+TAX_APPLY/100),2) TOTAL_BEFORE_DISCOUNT, ROUND(PRODUCT_PRICE_DISCOUNTED*(TAX_APPLY/100),2) TAX_AMOUNT" +
    ", PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL, TAX_ID, TAX_APPLY" +
    ", PRODUCT_PRICE_DISCOUNTED, ROUND(PRODUCT_PRICE_DISCOUNTED*(1+TAX_APPLY/100),2) TOTAL_AMOUNT " +
    ", (PRODUCT_PRICE-PRODUCT_PRICE_DISCOUNTED) DISCOUNT_AMOUNT" +
    ", case when ID_UNIT = 'LT' then 'Lt'" +
    "    when ID_UNIT = 'UNI' then 'Ud'" +
    "    when ID_UNIT = 'KG' then 'Kg'" +  
    "  end AS ID_UNIT" +
    ", REMARK, MIN_QUANTITY_SELL, PARTNER_ID, PARTNER_NAME, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE, PRODUCT_CATEGORY_ID, RN " +
    "FROM (" +
    "select A.PRODUCT_ID, A.PRODUCT_CODE, A.PRODUCT_NAME, A.PRODUCT_DESCRIPTION, D.PRODUCT_TYPE, A.BRAND, A.NUM_IMAGES, A.NUM_VIDEOS" +
	", A.PRODUCT_PRICE PRODUCT_PRICE, A.PRODUCT_PRICE_FINAL PRODUCT_PRICE_DISCOUNTED" +
    ", E.PERSONE_ID, E.PERSONE_NAME, E.BUSINESS_NAME, E.EMAIL, A.TAX_ID, F.TAX_APPLY" +
	", TIP_UNIDAD.ID_UNIT, A.REMARK, A.MIN_QUANTITY_SELL, A.PRODUCT_NAME_LONG, A.PARTNER_ID, A.PARTNER_NAME " +
    ", A.MODIFY_DATE, A.CREATE_DATE , A.QUANTITY_MIN_PRICE,  A.QUANTITY_MAX_PRICE, A.PRODUCT_CATEGORY_ID" +
    ", ROW_NUMBER() OVER (PARTITION BY A.PRODUCT_NAME, E.PERSONE_NAME ORDER BY A.PARTNER_ID DESC, IFNULL(A.MODIFY_DATE, A.CREATE_DATE) DESC, A.PRODUCT_PRICE_FINAL DESC, A.PRODUCT_ID DESC) AS RN " +
	"FROM (" +
	"        SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME_INTERNAL PRODUCT_NAME, PRODUCT_NAME PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE_ID, BRAND, REMARK, NUM_IMAGES" +
	"        , NUM_VIDEOS, PROVIDER_ID, TAX_ID, PRODUCT_PRICE , PRODUCT_PRICE_FINAL, PARTNER_ID, PARTNER_NAME" +
	"        , UNIT_ID, PRODUCT_CATEGORY_ID, IFNULL(MIN_QUANTITY_SELL, 1) AS MIN_QUANTITY_SELL" +
    "        , MODIFY_DATE, CREATE_DATE, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE" +
	"        FROM KRC_PRODUCT" +
	"        WHERE STATUS_ID='A' AND PARTNER_ID = 1" +
    "   ) A " +
	"LEFT OUTER JOIN (SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE FROM KRC_PRODUCT_TYPE WHERE STATUS_ID = 'A') D " +
	"ON (A.PRODUCT_TYPE_ID = D.PRODUCT_TYPE_ID) " +
    "LEFT OUTER JOIN (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) TIP_UNIDAD " +
    "ON (A.UNIT_ID = TIP_UNIDAD.CVE_UNIT) " +
    "LEFT OUTER JOIN (SELECT PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL FROM KRC_PERSONE_IDENTITY " +
    "WHERE STATUS_ID = 'A' AND PERSONE_TYPE = 'P') E " +
    "ON (A.PROVIDER_ID = E.PERSONE_ID) " +
    "LEFT OUTER JOIN (SELECT TAX_ID, TAX_APPLY FROM KRC_TAX_TYPE) F " +
    "ON (A.TAX_ID = F.TAX_ID) " +
	"ORDER BY PRODUCT_NAME" +
	") AA " +
    "ORDER BY PRODUCT_CATEGORY_ID, PERSONE_NAME, PARTNER_ID DESC, RN;";
	return query;
}
export function getProductAvailWithProductId (): string {
    const query = "SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE, BRAND, NUM_IMAGES, NUM_VIDEOS" +
    ", PRODUCT_PRICE, ROUND(PRODUCT_PRICE*(1+TAX_APPLY/100),2) TOTAL_BEFORE_DISCOUNT, ROUND(PRODUCT_PRICE_DISCOUNTED*(TAX_APPLY/100),2) TAX_AMOUNT" +
    ", PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL, TAX_ID, TAX_APPLY" +
    ", PRODUCT_PRICE_DISCOUNTED, ROUND(PRODUCT_PRICE_DISCOUNTED*(1+TAX_APPLY/100),2) TOTAL_AMOUNT " +
    ", (PRODUCT_PRICE-PRODUCT_PRICE_DISCOUNTED) DISCOUNT_AMOUNT" +
    ", case when ID_UNIT = 'LT' then 'Lt'" +
    "    when ID_UNIT = 'UNI' then 'Ud'" +
    "    when ID_UNIT = 'KG' then 'Kg'" +  
    "  end AS ID_UNIT" +
    ", REMARK, MIN_QUANTITY_SELL, PARTNER_ID, PARTNER_NAME, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE, PRODUCT_CATEGORY_ID, RN " +
    "FROM (" +
    "select A.PRODUCT_ID, A.PRODUCT_CODE, A.PRODUCT_NAME, A.PRODUCT_DESCRIPTION, D.PRODUCT_TYPE, A.BRAND, A.NUM_IMAGES, A.NUM_VIDEOS" +
	", A.PRODUCT_PRICE PRODUCT_PRICE, A.PRODUCT_PRICE_FINAL PRODUCT_PRICE_DISCOUNTED" +
    ", E.PERSONE_ID, E.PERSONE_NAME, E.BUSINESS_NAME, E.EMAIL, A.TAX_ID, F.TAX_APPLY" +
	", TIP_UNIDAD.ID_UNIT, A.REMARK, A.MIN_QUANTITY_SELL, A.PRODUCT_NAME_LONG, A.PARTNER_ID, A.PARTNER_NAME " +
    ", A.MODIFY_DATE, A.CREATE_DATE , A.QUANTITY_MIN_PRICE,  A.QUANTITY_MAX_PRICE, A.PRODUCT_CATEGORY_ID" +
    ", ROW_NUMBER() OVER (PARTITION BY A.PRODUCT_CATEGORY_ID, E.PERSONE_NAME ORDER BY A.PARTNER_ID DESC, IFNULL(A.MODIFY_DATE, A.CREATE_DATE) DESC, A.PRODUCT_PRICE_FINAL DESC, A.PRODUCT_ID DESC) AS RN " +
	"FROM (" +
	"        SELECT PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME_INTERNAL PRODUCT_NAME, PRODUCT_NAME PRODUCT_NAME_LONG, PRODUCT_DESCRIPTION, PRODUCT_TYPE_ID, BRAND, REMARK, NUM_IMAGES" +
	"        , NUM_VIDEOS, PROVIDER_ID, TAX_ID, PRODUCT_PRICE , PRODUCT_PRICE_FINAL, PARTNER_ID, PARTNER_NAME" +
	"        , UNIT_ID, PRODUCT_CATEGORY_ID, IFNULL(MIN_QUANTITY_SELL, 1) AS MIN_QUANTITY_SELL " +
    "        , MODIFY_DATE, CREATE_DATE, QUANTITY_MIN_PRICE, QUANTITY_MAX_PRICE" +
	"        FROM KRC_PRODUCT" +
	"        WHERE STATUS_ID='A' AND PRODUCT_ID = $1" +
    "   ) A " +
	"LEFT OUTER JOIN (SELECT PRODUCT_TYPE_ID, PRODUCT_TYPE FROM KRC_PRODUCT_TYPE WHERE STATUS_ID = 'A') D " +
	"ON (A.PRODUCT_TYPE_ID = D.PRODUCT_TYPE_ID) " +
    "LEFT OUTER JOIN (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) TIP_UNIDAD " +
    "ON (A.UNIT_ID = TIP_UNIDAD.CVE_UNIT) " +
    "LEFT OUTER JOIN (SELECT PERSONE_ID, PERSONE_NAME, BUSINESS_NAME, EMAIL FROM KRC_PERSONE_IDENTITY " +
    "WHERE STATUS_ID = 'A' AND PERSONE_TYPE = 'P') E " +
    "ON (A.PROVIDER_ID = E.PERSONE_ID) " +
    "LEFT OUTER JOIN (SELECT TAX_ID, TAX_APPLY FROM KRC_TAX_TYPE) F " +
    "ON (A.TAX_ID = F.TAX_ID) " +
	"ORDER BY PRODUCT_NAME" +
	") AA " +
    "ORDER BY PRODUCT_CATEGORY_ID, PERSONE_NAME, PARTNER_ID DESC, RN;";
	return query;
}
//
// get the last value for the sequence SEQ_PURCHASE
// 
export function queryPurchaseSequence (): string {
	const sql_query = "select KRRI.nextval('SEQ_PURCHASE') ORDER_ID, CAST(date_format(CONVERT_TZ( sysdate(), 'UTC', 'Europe/Paris'),'%Y%m%d') AS UNSIGNED) CURRENT_DAY;"
	return sql_query;
}
//
// get the purchases of the userId
//
export function queryGetPurchaseByUserIdOldVersion(): string {
    const query = 
    "SELECT ORDER_ID, PROVIDER_NAME" +
    ", CASE WHEN COUNT(DISTINCT STATUS_NAME)=1 THEN max(STATUS_NAME)" +
    "    ELSE 'VARIOS' END ALL_STATUS" +
    ", CASE WHEN COUNT(DISTINCT STATUS_ID)=1 THEN max(STATUS_ID)" +
    "    ELSE 'VARIOS' END STATUS_ID" +
    ", COUNT(DISTINCT STATUS_NAME) NUM_STATUS" +
    ", SUM(QUANTITY) ITEMS, MAX(SITUACION) SITUACION, SUM(TOTAL_AMOUNT) TOTAL_AMOUNT, SUM(TAX_AMOUNT) TAX_AMOUNT, SUM(DISCOUNT_AMOUNT) DISCOUNT_AMOUNT" +
    ", SUM(PRODUCT_PRICE_FINAL) PRODUCT_PRICE_FINAL , SUM(PRODUCT_PRICE) PRODUCT_PRICE " +
    ", SUM(TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX " + 
    ", SUM(TOTAL_AFTER_DISCOUNT_WITHOUT_TAX) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, MAX(ORDER_DATE) ORDER_DATE " +
    "FROM (" +
    "    SELECT ORDER_ID, A.PRODUCT_NAME, A.PRODUCT_ID, PROVIDER_NAME" +
    "    , CASE WHEN A.STATUS_ID IN ('E','F','P','S','O','D') THEN 'ABIERTO'" +
    "        ELSE 'CERRADO' END SITUACION" +
    "    , TOTAL_AMOUNT" +
    "    , TAX_AMOUNT" +
    "    , DISCOUNT_AMOUNT" +
    "    , (A.PRODUCT_PRICE - (DISCOUNT_AMOUNT/QUANTITY)) PRODUCT_PRICE_FINAL" +
    "    , QUANTITY, TAX_APPLY, C.STATUS_ID, C.STATUS_NAME, A.PRODUCT_PRICE " +
    "    , (QUANTITY * A.PRODUCT_PRICE) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX " +
    "    , ((QUANTITY * A.PRODUCT_PRICE) - DISCOUNT_AMOUNT) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, ORDER_DATE" +
    "    FROM KRC_PURCHASE A, KRC_TAX_TYPE B," +
    "          (SELECT STATUS_OBJECT_ID STATUS_ID, STATUS_NAME FROM KRC_STATUS GROUP BY STATUS_OBJECT_ID, STATUS_NAME) C" +
    "    WHERE " +
    "      (ORDER_DATE >= DATE_ADD(CURRENT_DATE(), interval -2 MONTH) OR A.STATUS_ID IN ('E','F','P','S','O','D'))" +
    "      AND A.TAX_ID=B.TAX_ID AND A.STATUS_ID=C.STATUS_ID AND USER_CREATE_ID = $1 " +
    "    ) AA " +
    "GROUP BY ORDER_ID, PROVIDER_NAME;"
    ;
    return query;
}
export function queryGetPurchaseByUserId(): string {
    const query = 
    "SELECT ORDER_ID, PROVIDER_NAME, BUYER_NAME, SHOW_NAME" +
    ", CASE WHEN COUNT(DISTINCT STATUS_NAME)=1 THEN max(STATUS_NAME)" +
    "    ELSE 'VARIOS' END ALL_STATUS" +
    ", CASE WHEN COUNT(DISTINCT STATUS_ID)=1 THEN max(STATUS_ID)" +
    "    ELSE 'VARIOS' END STATUS_ID" +
    ", COUNT(DISTINCT STATUS_NAME) NUM_STATUS" +
    ", NVL(SUM(CASE WHEN NEW_QUANTITY IS NULL THEN QUANTITY ELSE NEW_QUANTITY END), 0) ITEMS" +
    ", MAX(SITUACION) SITUACION, NVL(SUM(TOTAL_AMOUNT), 0) TOTAL_AMOUNT, NVL(SUM(TAX_AMOUNT), 0) TAX_AMOUNT, NVL(SUM(DISCOUNT_AMOUNT), 0) DISCOUNT_AMOUNT" +
    ", NVL(SUM(PRODUCT_PRICE_FINAL), 0) PRODUCT_PRICE_FINAL , NVL(SUM(PRODUCT_PRICE), 0) PRODUCT_PRICE " +
    ", NVL(SUM(TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX), 0) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX " + 
    ", NVL(SUM(TOTAL_AFTER_DISCOUNT_WITHOUT_TAX), 0) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, MAX(ORDER_DATE) ORDER_DATE " +
    "FROM (" +
    "    SELECT ORDER_ID, A.PRODUCT_NAME, A.PRODUCT_ID, A.PROVIDER_NAME" +
    "    , CASE WHEN D.PARTNER_ID=1 AND J.PERSONE_TYPE='P' THEN J.PERSONE_NAME" +
    "           ELSE D.PARTNER_NAME END BUYER_NAME" +
    "    , CASE WHEN D.PARTNER_ID=1 AND J.PERSONE_TYPE='P' THEN J.PERSONE_NAME" +
    "           WHEN J.PERSONE_TYPE = 'P' THEN D.PARTNER_NAME" +
    "           ELSE A.PROVIDER_NAME END SHOW_NAME" +
    "    , CASE WHEN A.STATUS_ID IN ('E','F','P','S','O','D') THEN 'ABIERTO'" +
    "        ELSE 'CERRADO' END SITUACION" +
    "    , A.TOTAL_AMOUNT" +
    "    , A.TAX_AMOUNT" +
    "    , A.DISCOUNT_AMOUNT" +
    "    , (A.PRODUCT_PRICE - (A.DISCOUNT_AMOUNT/A.QUANTITY)) PRODUCT_PRICE_FINAL" +
    "    , A.QUANTITY, A.NEW_QUANTITY, B.TAX_APPLY, C.STATUS_ID, C.STATUS_NAME, A.PRODUCT_PRICE " +
    "    , (A.QUANTITY * A.PRODUCT_PRICE) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX " +
    "    , ((A.QUANTITY * A.PRODUCT_PRICE) + A.DISCOUNT_AMOUNT) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, A.ORDER_DATE" +
    "    FROM KRC_PURCHASE A, KRC_TAX_TYPE B," +
    "          (SELECT STATUS_OBJECT_ID STATUS_ID, STATUS_NAME FROM KRC_STATUS GROUP BY STATUS_OBJECT_ID, STATUS_NAME) C" +
    "          ,KRC_PRODUCT D, KRC_PERSONE_IDENTITY E, KRC_PERSONE_IDENTITY H" +
    "          , (SELECT * FROM (SELECT PERSONE_ID, PERSONE_TYPE, PERSONE_NAME, USER_ID, PARTNER_NAME, PARTNER_ID" +
    "             , ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY PERSONE_ID)  AS RN  FROM KRC_PERSONE_IDENTITY  ) BB WHERE RN=1) J" +
    "    WHERE " +
    "      (A.ORDER_DATE >= DATE_ADD(CURRENT_DATE(), interval -2 MONTH) OR A.STATUS_ID IN ('E','F','P','S','O','D'))" +
    "      AND A.TAX_ID=B.TAX_ID AND A.STATUS_ID=C.STATUS_ID AND A.USER_CREATE_ID = E.USER_ID" +
    "      AND A.PRODUCT_ID=D.PRODUCT_ID AND D.PROVIDER_ID = H.PERSONE_ID" +
    "      AND $1 = J.USER_ID" +
    "      AND (A.USER_CREATE_ID = $1 " +
    "        OR $1 IN (SELECT I.USER_ID " +
    "                    FROM KRC_PERSONE_IDENTITY I WHERE I.STATUS_ID = 'A' AND I.PARTNER_ID = E.PARTNER_ID" +
    "                    GROUP BY I.USER_ID" +
    "                 )" +
    "        OR $1 IN (SELECT F.USER_ID" +
    "                    FROM KRC_PERSONE_IDENTITY F, KRR_USER_ROLE G" +
    "                    WHERE F.STATUS_ID = 'A' AND F.USER_ID=G.USER_ID AND G.ROLE_ID=2 AND NVL(F.PARTNER_ID,1) != 1" +
    "                    AND F.PARTNER_ID = H.PARTNER_ID" +
    "                    GROUP BY F.USER_ID" +
    "                 )" +
    "        )" +
//    "        AND ORDER_ID = 691" +
    "    ) AA " +
    "GROUP BY ORDER_ID, PROVIDER_NAME, BUYER_NAME, SHOW_NAME;"
    ;
    return query;
}
//
// get the purchase detail of the userId
//
export function queryGetPurchaseLinesByOrderIdOld(): string {
    const query = 
    "SELECT ORDER_ID, PROVIDER_NAME, PRODUCT_ID, PRODUCT_NAME" +
    ", CASE WHEN COUNT(DISTINCT STATUS_NAME)=1 THEN max(STATUS_NAME)" +
    "    ELSE 'VARIOS' END ALL_STATUS" +
    ", CASE WHEN COUNT(DISTINCT STATUS_ID)=1 THEN max(STATUS_ID)" +
    "    ELSE 'VARIOS' END STATUS_ID" +
    ", COUNT(DISTINCT STATUS_NAME) NUM_STATUS" +
    ", max(BAN_PRICE) BAN_PRICE" +
    ", max(BAN_QUANTITY) BAN_QUANTITY" +
    ", NVL(SUM(QUANTITY), 0) ITEMS, NVL(SUM(NEW_QUANTITY), -1) NEW_QUANTITY" +
    ", NVL(SUM(NEW_PRODUCT_PRICE_FINAL), -1) NEW_PRODUCT_PRICE_FINAL , MAX(BAN_OFICIAL_PRICE) BAN_OFICIAL_PRICE" + 
    ", MAX(SITUACION) SITUACION, NVL(SUM(TOTAL_AMOUNT), 0) TOTAL_AMOUNT, NVL(SUM(TAX_AMOUNT), 0) TAX_AMOUNT, NVL(SUM(DISCOUNT_AMOUNT), 0) DISCOUNT_AMOUNT" +
    ", NVL(SUM(PRODUCT_PRICE_FINAL), 0) PRODUCT_PRICE_FINAL , NVL(SUM(PRODUCT_PRICE),0) PRODUCT_PRICE " +
    ", NVL(SUM(TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX), 0) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX " + 
    ", NVL(SUM(TOTAL_AFTER_DISCOUNT_WITHOUT_TAX), 0) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, MAX(ORDER_DATE) ORDER_DATE " +
    ", MAX(REMARK_SELLER) REMARK_SELLER, MAX(REMARK_BUYER) REMARK_BUYER " +
    "FROM (" +
    "    SELECT ORDER_ID, PRODUCT_NAME, PRODUCT_ID, PROVIDER_NAME" +
    "    , CASE WHEN A.STATUS_ID IN ('E','F','P','S','O','D') THEN 'ABIERTO'" +
    "        ELSE 'CERRADO' END SITUACION" +
    "    , TOTAL_AMOUNT" +
    "    , TAX_AMOUNT" +
    "    , DISCOUNT_AMOUNT" +
    "    , (PRODUCT_PRICE - (DISCOUNT_AMOUNT/QUANTITY)) PRODUCT_PRICE_FINAL" +
    "    , QUANTITY,  NEW_QUANTITY, NEW_PRODUCT_PRICE_FINAL, BAN_OFICIAL_PRICE, TAX_APPLY, C.STATUS_ID, C.STATUS_NAME, C.BAN_PRICE, C.BAN_QUANTITY, PRODUCT_PRICE" +
    "    , (QUANTITY * PRODUCT_PRICE) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX " +
    "    , ((QUANTITY * PRODUCT_PRICE) + DISCOUNT_AMOUNT) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, ORDER_DATE" +
    "    , REMARK_SELLER, REMARK_BUYER " +
    "    FROM KRC_PURCHASE A, KRC_TAX_TYPE B," +
    "        (SELECT" +
    "           KRC_STATUS.STATUS_OBJECT_ID STATUS_ID, KRC_STATUS.STATUS_NAME" +
    "           , MAX(KRC_STATUS.BAN_PRICE) BAN_PRICE, MAX(KRC_STATUS.BAN_QUANTITY) BAN_QUANTITY" +
    "         FROM KRC_STATUS, KRR_USER_ROLE, KRC_ROLE" +
    "         WHERE KRR_USER_ROLE.USER_ID = $3 AND KRR_USER_ROLE.ROLE_ID = KRC_ROLE.ROLE_ID" +
    "           AND KRC_ROLE.ROLE_NAME = KRC_STATUS.ROLE" +
    "         GROUP BY KRC_STATUS.STATUS_OBJECT_ID, KRC_STATUS.STATUS_NAME" +
    "        ) C" +
    "    WHERE ORDER_ID = $1 AND PROVIDER_NAME = $2 " +
    "      AND A.TAX_ID=B.TAX_ID AND A.STATUS_ID=C.STATUS_ID " +
    "    ) AA " +
    "GROUP BY ORDER_ID, PROVIDER_NAME, PRODUCT_ID, TAX_APPLY, STATUS_NAME;"
    ;
    return query;
}

export function queryGetPurchaseLinesByOrderId(): string {
    const query = 
    "SELECT ORDER_ID, PROVIDER_NAME, PRODUCT_ID, PRODUCT_NAME" +
    ", CASE WHEN COUNT(DISTINCT STATUS_NAME)=1 THEN max(STATUS_NAME)" +
    "    ELSE 'VARIOS' END ALL_STATUS" +
    ", CASE WHEN COUNT(DISTINCT STATUS_ID)=1 THEN max(STATUS_ID)" +
    "    ELSE 'VARIOS' END STATUS_ID" +
    ", COUNT(DISTINCT STATUS_NAME) NUM_STATUS" +
    ", max(BAN_PRICE) BAN_PRICE" +
    ", max(BAN_QUANTITY) BAN_QUANTITY" +
    ", NVL(SUM(QUANTITY), 0) ITEMS" +
    ", case when ID_UNIT = 'LT' then 'Lt'" +
    "  when ID_UNIT = 'UNI' then 'Ud'" +
    "  when ID_UNIT = 'KG' then 'Kg'" +
    "end AS ID_UNIT" +
    ", NVL(SUM(NEW_QUANTITY), -1) NEW_QUANTITY" +
    ", NVL(SUM(NEW_PRODUCT_PRICE_FINAL), -1) NEW_PRODUCT_PRICE_FINAL , MAX(BAN_OFICIAL_PRICE) BAN_OFICIAL_PRICE" + 
    ", MAX(SITUACION) SITUACION, NVL(SUM(TOTAL_AMOUNT), 0) TOTAL_AMOUNT, NVL(SUM(TAX_AMOUNT), 0) TAX_AMOUNT, NVL(SUM(DISCOUNT_AMOUNT), 0) DISCOUNT_AMOUNT" +
    ", NVL(SUM(PRODUCT_PRICE_FINAL), 0) PRODUCT_PRICE_FINAL , NVL(SUM(PRODUCT_PRICE),0) PRODUCT_PRICE " +
    ", NVL(SUM(TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX), 0) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX " + 
    ", NVL(SUM(TOTAL_AFTER_DISCOUNT_WITHOUT_TAX), 0) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, MAX(ORDER_DATE) ORDER_DATE " +
    ", MAX(REMARK_SELLER) REMARK_SELLER, MAX(REMARK_BUYER) REMARK_BUYER " +
    "FROM (" +
    "    SELECT ORDER_ID, PRODUCT_NAME, A.PRODUCT_ID, PROVIDER_NAME, E.ID_UNIT ID_UNIT" +
    "    , CASE WHEN A.STATUS_ID IN ('E','F','P','S','O','D') THEN 'ABIERTO'" +
    "        ELSE 'CERRADO' END SITUACION" +
    "    , TOTAL_AMOUNT" +
    "    , TAX_AMOUNT" +
    "    , DISCOUNT_AMOUNT" +
    "    , (PRODUCT_PRICE - (DISCOUNT_AMOUNT/QUANTITY)) PRODUCT_PRICE_FINAL" +
    "    , QUANTITY,  NEW_QUANTITY, NEW_PRODUCT_PRICE_FINAL, BAN_OFICIAL_PRICE, TAX_APPLY, C.STATUS_ID, C.STATUS_NAME, C.BAN_PRICE, C.BAN_QUANTITY, PRODUCT_PRICE" +
    "    , (QUANTITY * PRODUCT_PRICE) TOTAL_BEFORE_DISCOUNT_WITHOUT_TAX " +
    "    , ((QUANTITY * PRODUCT_PRICE) + DISCOUNT_AMOUNT) TOTAL_AFTER_DISCOUNT_WITHOUT_TAX, ORDER_DATE" +
    "    , REMARK_SELLER, REMARK_BUYER " +
    "    FROM KRC_PURCHASE A, KRC_TAX_TYPE B," +
    "        (SELECT" +
    "           KRC_STATUS.STATUS_OBJECT_ID STATUS_ID, KRC_STATUS.STATUS_NAME" +
    "           , MAX(KRC_STATUS.BAN_PRICE) BAN_PRICE, MAX(KRC_STATUS.BAN_QUANTITY) BAN_QUANTITY" +
    "         FROM KRC_STATUS, KRR_USER_ROLE, KRC_ROLE" +
    "         WHERE KRR_USER_ROLE.USER_ID = $3 AND KRR_USER_ROLE.ROLE_ID = KRC_ROLE.ROLE_ID" +
    "           AND KRC_ROLE.ROLE_NAME = KRC_STATUS.ROLE" +
    "         GROUP BY KRC_STATUS.STATUS_OBJECT_ID, KRC_STATUS.STATUS_NAME" +
    "        ) C, " +
    "        (SELECT PRODUCT_ID, UNIT_ID FROM KRC_PRODUCT) D," +
    "        (SELECT CVE_UNIT, ID_UNIT FROM DMD_UNIT) E " +
    "    WHERE ORDER_ID = $1 AND PROVIDER_NAME = $2 " +
    "      AND A.TAX_ID=B.TAX_ID AND A.STATUS_ID=C.STATUS_ID AND A.PRODUCT_ID = D.PRODUCT_ID AND D.UNIT_ID = E.CVE_UNIT " +
    "    ) AA " +
    "GROUP BY ORDER_ID, PROVIDER_NAME, PRODUCT_ID, TAX_APPLY, STATUS_NAME;"
    ;
    return query;
}
//
//
//
export function queryGetStatusPurchase(): string {
    const query = 
    "SELECT " +
    "  ORDER_ID, PROVIDER_NAME" +
    "  ,CASE WHEN COUNT(DISTINCT STATUS_NAME)=1 THEN max(STATUS_NAME)" +
    "  ELSE 'VARIOS' END ALL_STATUS" +
    "  , CASE WHEN COUNT(DISTINCT STATUS_ID)=1 THEN max(STATUS_ID)" +
    "		ELSE 'VARIOS' END STATUS_ID" +
    "  , COUNT(DISTINCT STATUS_NAME) NUM_STATUS " +
    "FROM " +
    "(" +
    "   SELECT A.ORDER_ID, A.PROVIDER_NAME, C.STATUS_ID, C.STATUS_NAME" +
    "   FROM KRC_PURCHASE A," +
    "		(SELECT STATUS_OBJECT_ID STATUS_ID, STATUS_NAME " +
    "        FROM KRC_STATUS " +
    "        GROUP BY STATUS_OBJECT_ID, STATUS_NAME) C " +
    "   WHERE A.ORDER_ID = $1 AND A.PROVIDER_NAME = $2" +
    "     AND A.STATUS_ID=C.STATUS_ID" +
    ") AA " +
    "GROUP BY ORDER_ID, PROVIDER_NAME;";
    return query;
}
//
// update the status of the purchase
//
export function queryUpdatePurchaseState(): string {
    const query = 
    "UPDATE KRC_PURCHASE SET STATUS_ID = $1, USER_MODIFY_ID = $2, MODIFY_DATE = $3 WHERE ORDER_ID = $4 AND PROVIDER_NAME= $5;";
    return query;
}
//
// update the status of the purchase line
//
export function queryUpdatePurchaseLineState(): string {
    const query = 
    "UPDATE KRC_PURCHASE SET STATUS_ID = $1, USER_MODIFY_ID = $2, MODIFY_DATE = $3 " + 
    "WHERE ORDER_ID = $4 AND PROVIDER_NAME= $5 and PRODUCT_ID = $6;";
    return query;
}
export function queryUpdatePurchaseLine (caseToApply: number, userRole: string): string {
    let query: string;
    // Case 1
    // The price and the quantity of the purchased has been changed by the user
    const queryCaseToApply1ForBuyer = 
    "UPDATE KRC_PURCHASE SET NEW_QUANTITY = $1, NEW_PRODUCT_PRICE_FINAL = $2, " + 
    "BAN_OFICIAL_PRICE = $3, TOTAL_BEFORE_DISCOUNT = $4, TOTAL_AMOUNT = $5, " +
    "DISCOUNT_AMOUNT = $6, TAX_AMOUNT = $7, USER_MODIFY_ID = $8, MODIFY_DATE = $9, STATUS_ID = 'O', REMARK_BUYER = $10 " +
    "WHERE ORDER_ID = $11 AND PROVIDER_NAME= $12 AND PRODUCT_ID = $13;";
    const queryCaseToApply1ForSeller = 
    "UPDATE KRC_PURCHASE SET NEW_QUANTITY = $1, NEW_PRODUCT_PRICE_FINAL = $2, " + 
    "BAN_OFICIAL_PRICE = $3, TOTAL_BEFORE_DISCOUNT = $4, TOTAL_AMOUNT = $5, " +
    "DISCOUNT_AMOUNT = $6, TAX_AMOUNT = $7, USER_MODIFY_ID = $8, MODIFY_DATE = $9, STATUS_ID = 'O', REMARK_SELLER = $10 " +
    "WHERE ORDER_ID = $11 AND PROVIDER_NAME= $12 AND PRODUCT_ID = $13;";
    // Case 2
    // Only the price of the purchased has been changed by the user
    const queryCaseToApply2ForBuyer = 
    "UPDATE KRC_PURCHASE SET NEW_PRODUCT_PRICE_FINAL = $1, " + 
    "BAN_OFICIAL_PRICE = $2, TOTAL_BEFORE_DISCOUNT = $3, TOTAL_AMOUNT = $4, " +
    "DISCOUNT_AMOUNT = $5, TAX_AMOUNT = $6, USER_MODIFY_ID = $7, MODIFY_DATE = $8, STATUS_ID = 'O', REMARK_BUYER = $9 " + 
    "WHERE ORDER_ID = $10 AND PROVIDER_NAME= $11 AND PRODUCT_ID = $12;";
    const queryCaseToApply2ForSeller = 
    "UPDATE KRC_PURCHASE SET NEW_PRODUCT_PRICE_FINAL = $1, " + 
    "BAN_OFICIAL_PRICE = $2, TOTAL_BEFORE_DISCOUNT = $3, TOTAL_AMOUNT = $4, " +
    "DISCOUNT_AMOUNT = $5, TAX_AMOUNT = $6, USER_MODIFY_ID = $7, MODIFY_DATE = $8, STATUS_ID = 'O', REMARK_SELLER = $9 " + 
    "WHERE ORDER_ID = $10 AND PROVIDER_NAME= $11 AND PRODUCT_ID = $12;";
    // Case 3
    // Only the quantity has been changed by the user
    const queryCaseToApply3ForBuyer =
    "UPDATE KRC_PURCHASE SET NEW_QUANTITY = $1, " +
    "TOTAL_BEFORE_DISCOUNT = $2, TOTAL_AMOUNT = $3, " +
    "DISCOUNT_AMOUNT = $4, TAX_AMOUNT = $5, USER_MODIFY_ID = $6, MODIFY_DATE = $7, STATUS_ID = 'O', REMARK_BUYER = $8 " +
    "WHERE ORDER_ID = $9 AND PROVIDER_NAME= $10 AND PRODUCT_ID = $11;";
    const queryCaseToApply3ForSeller =
    "UPDATE KRC_PURCHASE SET NEW_QUANTITY = $1, " +
    "TOTAL_BEFORE_DISCOUNT = $2, TOTAL_AMOUNT = $3, " +
    "DISCOUNT_AMOUNT = $4, TAX_AMOUNT = $5, USER_MODIFY_ID = $6, MODIFY_DATE = $7, STATUS_ID = 'O', REMARK_SELLER = $8 " +
    "WHERE ORDER_ID = $9 AND PROVIDER_NAME= $10 AND PRODUCT_ID = $11;";
    if (caseToApply == 1) {
        // Case 1
        // The price and the quantity of the purchased has been changed by the user
        if (userRole == 'BUYER') {
            query = queryCaseToApply1ForBuyer;
        } else {
            query = queryCaseToApply1ForSeller;
        }
    } else if (caseToApply == 2) {
        // Case 2
        // Only the price of the purchased has been changed by the user
        if (userRole == 'BUYER') {
            query = queryCaseToApply2ForBuyer;
        } else {
            query = queryCaseToApply2ForSeller;
        }
    }else if (caseToApply == 3) {
        // Case 3
        // Only the quantity has been changed by the user
        if (userRole == 'BUYER') {
            query = queryCaseToApply3ForBuyer;
        } else {
            query = queryCaseToApply3ForSeller;
        }
    } else {
        // anyway Case 1
        // The price and the quantity of the purchased has been changed by the user
        if (userRole == 'BUYER') {
            query = queryCaseToApply1ForBuyer;
        } else {
            query = queryCaseToApply1ForSeller;
        }
    }
    return query;
}
//
// get the status of the purchase
//
export function getStatusToTransitionToDeprecated(): string {
    const query=
        "SELECT " + 
        "A.DESTINATION_STATUS_ID, E.STATUS_NAME, B.BAN_PRICE, B.BAN_QUANTITY, A.PRIORITY, D.ROLE_NAME " +
        "FROM" +
        "  KRC_STATUS_FLOW A, KRC_STATUS B, KRR_USER_ROLE C, KRC_ROLE D, KRC_STATUS E " +
        "WHERE A.STATUS_OBJECT='P'" +
        "  AND A.ORIGIN_STATUS_ID=$1 AND C.USER_ID=$2" +
        "  AND A.ROLE=B.ROLE AND A.ORIGIN_STATUS_ID=B.STATUS_OBJECT_ID AND A.DESTINATION_STATUS_ID = E.STATUS_OBJECT_ID AND A.ROLE=E.ROLE" +
        "  AND C.ROLE_ID=D.ROLE_ID AND ROLE_NAME IN ('BUYER','SELLER')" +
        "  AND A.ROLE=D.ROLE_NAME " +
        "ORDER BY PRIORITY;"
        ;
    return query;
}
export function getStatusToTransitionTo(): string {
    const query=
        "SELECT " + 
        "A.DESTINATION_STATUS_ID, D.STATUS_NAME, D.BAN_PRICE, D.BAN_QUANTITY, A.PRIORITY, C.ROLE_NAME " +
        "FROM" +
        "  KRC_STATUS_FLOW A, KRR_USER_ROLE B, KRC_ROLE C, KRC_STATUS D " +
        "WHERE " +
        "  B.USER_ID = $2" +
        "  AND B.STATUS_ID = 'A'" +
        "  AND B.ROLE_ID = C.ROLE_ID" +
        "  AND A.ROLE = C.ROLE_NAME" +
        "  AND A.ORIGIN_STATUS_ID = $1" +
        "  AND A.STATUS_ID = 'A'" +
        "  AND A.STATUS_OBJECT = 'P'" +
        "  AND D.STATUS_ID = 'A'" +
        "  AND D.STATUS_OBJECT = 'P'" +
        "  AND D.ROLE = C.ROLE_NAME" +
        "  AND A.DESTINATION_STATUS_ID = D.STATUS_OBJECT_ID " +
        "ORDER BY A.PRIORITY"
        ;
    return query;
}
export function getBanPriceUndBanQuantityValues(): string {
    const query =
        "SELECT " + 
        "KRC_STATUS.STATUS_OBJECT_ID DESTINATION_STATUS_ID, KRC_STATUS.STATUS_NAME " +
        ", KRC_STATUS.BAN_PRICE BAN_PRICE, KRC_STATUS.BAN_QUANTITY BAN_QUANTITY, 1 PRIORITY, KRC_STATUS.ROLE ROLE_NAME " +
        "FROM " +
        "KRC_STATUS, KRR_USER_ROLE, KRC_ROLE " +
        "WHERE KRR_USER_ROLE.USER_ID = $1 AND KRR_USER_ROLE.ROLE_ID = KRC_ROLE.ROLE_ID " +
        "AND KRC_ROLE.ROLE_NAME = KRC_STATUS.ROLE " +
        "AND KRC_STATUS.STATUS_OBJECT_ID = $2 " +
        "LIMIT 1;";
    return query;
}
//
// Mark the products that have been purchased in the KRC_PRODUCT_AVAIL table
// 
export function queryInsertPurchased (): string {
    const query =
    "INSERT INTO KRC_PURCHASE( " +
    "ORDER_ID " +
    ", INVOICE_ID" +
    ", PROVIDER_NAME" +
    ", PRODUCT_NAME" +
    ", PRODUCT_ID" +
    ", QUANTITY" +
    ", PRODUCT_PRICE" +
    ", TOTAL_BEFORE_DISCOUNT" +
    ", TOTAL_AMOUNT" +
    ", OPEN_AMOUNT" +
    ", DISCOUNT_AMOUNT" +
    ", TAX_ID" +
    ", TAX_AMOUNT" +
    ", ORDER_DATE" +
    ", PRODUCT_ENTRY_DATE" +
    ", CLOSE_DATE" +
    ", STATUS_DATE" +
    ", MODIFY_DATE" +
    ", STATUS_ID" +
    ", USER_CREATE_ID" +
    ", USER_MODIFY_ID" +
    ", SCENARIO" +
    ", PARTNER_ID" +
    ", PARTNER_NAME" +
    ", PAYMENT_METHOD" +
    ", ADDR_ID" +
    ", CONTACT_ID" +
    ", CONTACT_NAME" +
    ", CONTACT_POSITION" +
    ", CONTACT_PHONE" +
    ", EMAIL" +
    ", DELIVERY_DATE" +
    ", DISCOUNT_TYPE" +
    ") " +
    "VALUES " +
    "(" +
    "$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, " +
    "sysdate(), sysdate(), sysdate(), sysdate(), sysdate(), 'E', $14, null, 'APP', $15, $16, " +
    "'', 0, 0, '', null, '', '', sysdate(), 'PCT'" +
    ");"
    ;
    return query;
}
//
// get the last value for the sequence SEQ_TRANSACTIONS
// 
export function queryTransactionsSequence (): string {
	const sql_query = "select KRRI.nextval('SEQ_TRANSACTIONS') TRANSACTION_ID;"
	return sql_query;
}
//
// insert into KRF_TRANSACTIONS the last status update
// 
export function querySaveTransaction (): string {
	const sql_insercion = "INSERT INTO `KRF_TRANSACTIONS` (" + 
	"`order_id`, `day`, `hour`, `company_id`, `period_id`, `employee_id`, `payroll_day`, " + 
	"`max_salary`, `extracted_amount`, `trans_type`, `product_id`, `create_date`,`scenario`, `origen`, `destino`) " + 
	"VALUES (" + 
	"$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15" +
	");";
	return sql_insercion;
}
//
// Mark the products that have been purchased in the KRC_PRODUCT_AVAIL table
// 
export function updateProductsAvail (): string {
	const sql_update = 
	"UPDATE `KRC_PRODUCT_AVAIL` SET USER_MODIFY_ID=$1, MODIFY_DATE = CONVERT_TZ( sysdate(), 'UTC', 'America/Mexico_City') \n" + 
	"WHERE ORDER_ID IN \n" +
	"(\n" +
	"SELECT\n" + 
	"ORDER_ID\n" +
	"FROM \n" +
	"(SELECT\n" +
	"ORDER_ID\n" +
	" , ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY PRODUCT_AVAIL_ID ) AS RN\n" + 
	"FROM KRC_PRODUCT_AVAIL\n" +
	"WHERE  QUANTITY>0 AND PRODUCT_ID =$2\n"+
	"AND USER_MODIFY_ID=1\n"+
	") AA WHERE AA.RN <= $3\n"+
	")"+
	";"
	;
	return sql_update;
}
//
// Insert in the KRF_TRANSACTIONS table the products that have been marked in KRC_PRODUCT_AVAIL
// 
export function addMarkedPruductsToTransactions (): string {
	const sql_insert = "INSERT INTO `KRF_TRANSACTIONS`\n" +
	"(\n" +
	"`DAY`\n" +
	", `HOUR`\n" +
	", `TRANSACTION_ID`\n" +
	", `COMPANY_ID`\n" +
	", `PERIOD_ID`\n" +
	", `EMPLOYEE_ID`\n" +
	", `BANK_ACCOUNT_ID`\n" +
	", `PAYROLL_DAY`\n" +
	", `AGR_SALARY`\n" +
	", `MAX_SALARY`\n" +
	", `EXTRACTED_AMOUNT`\n" +
	", `COMISSION_AMOUNT`\n" +
	", `TRANS_TYPE`\n" +
	", `PRODUCT_ID`\n" +
	", `PRODUCT_CODE`\n" +
	", `ORDER_ID`\n" +
	", `CREATE_DATE`\n" +
	", `EXP_DATE`\n" +
	", `SCENARIO`\n" +
	")\n" +
	"SELECT\n" +
	"CAST(date_format(CONVERT_TZ( sysdate(), 'UTC', 'America/Mexico_City'),'%Y%m%d') AS UNSIGNED) DAY\n" +
	", DATE_FORMAT(CONVERT_TZ( sysdate(), 'UTC', 'America/Mexico_City'), '%H:%i:%S' ) HOUR\n" +
	", nextval('SEQ_TRANSACTIONS') TRANSACTION_ID\n" +
	", $1 COMPANY_ID\n" +
	", $2 PERIOD_ID\n" +
	", $3 EMPLOYEE_ID\n" +
	", $4 BANK_ACCOUNT_ID\n" +
	", $5 PAYROLL_DAY\n" +
	", $6 AGR_SALARY\n" +
	", $7 MAX_SALARY\n" +
	", $8 EXTRACTED_AMOUNT\n" +
	", $9 COMISSION_AMOUNT\n" +
	", 'P' TRANS_TYPE\n" +
	", PRODUCT_ID\n" +
	", PRODUCT_CODE\n" +
	", ORDER_ID\n" +
	", CONVERT_TZ( sysdate(), 'UTC', 'America/Mexico_City') CREATE_DATE\n" +
	", DATE_ADD(sysdate(), interval DAYS_EXP DAY) EXP_DATE\n" +
	", 'N' SCENARIO\n" +
	"FROM\n" +
	"(SELECT\n" +
	"KRC_PRODUCT_AVAIL.ORDER_ID ORDER_ID, KRC_PRODUCT_AVAIL.PRODUCT_ID PRODUCT_ID, KRC_PRODUCT.PRODUCT_CODE PRODUCT_CODE, (KRC_PRODUCT_AVAIL.PRODUCT_PRICE/10000) PRODUCT_PRICE\n" +
	", KRC_PRODUCT.DAYS_EXP DAYS_EXP\n" +
	"FROM KRC_PRODUCT_AVAIL\n" +
	"INNER JOIN KRC_PRODUCT ON (KRC_PRODUCT_AVAIL.PRODUCT_ID = KRC_PRODUCT.PRODUCT_ID)\n" +
	"WHERE  QUANTITY>0 AND KRC_PRODUCT_AVAIL.PRODUCT_ID =$10\n" +
	"AND KRC_PRODUCT_AVAIL.USER_MODIFY_ID=$11\n" +
	") MARCADOS;";

	return sql_insert;
}
//
// Take the registrys that habe been inserted to return them to the client
// 
export function queryMarkedPruductsToTransactions (): string {

	const sql_query =
	"SELECT\n" +
	"KRF_TRANSACTIONS.ORDER_ID\n" +
	", KRF_TRANSACTIONS.DAY\n" +
	", KRF_TRANSACTIONS.HOUR\n" +
	", KRF_TRANSACTIONS.PERIOD_ID\n" +
	", KRC_BANK_ACCOUNT.ACCT_NO\n" +
	", ROUND(KRF_TRANSACTIONS.AGR_SALARY) AGR_SALARY\n" +
	", ROUND(KRF_TRANSACTIONS.MAX_SALARY) MAX_SALARY\n" +
	", ROUND(KRF_TRANSACTIONS.EXTRACTED_AMOUNT) EXTRACTED_AMOUNT\n" +
	", ROUND(KRF_TRANSACTIONS.COMISSION_AMOUNT) COMISSION_AMOUNT\n" +
	", KRC_PRODUCT.PRODUCT_ID\n" +
	", KRC_PRODUCT.PRODUCT_NAME\n" +
	", KRC_PRODUCT.PRODUCT_CODE\n" +
	", KRC_PRODUCT.PRODUCT_ID\n" +
	", KRC_PRODUCT.PRODUCT_NAME\n" +
	", KRC_PRODUCT.PRODUCT_CODE\n" +
	", KRC_PRODUCT.PRODUCT_DESCRIPTION\n" +
	", KRC_PRODUCT_TYPE.PRODUCT_TYPE\n" +
	", KRC_PRODUCT.BRAND\n" +
	", KRC_PRODUCT.IMAGE\n" +
	", '0' AVAIL\n" +
	", '0' PRODUCT_PRICE\n" +
	", '0' COMISSION\n" +
	", KRC_PRODUCT.REMARK\n" +
	"FROM\n" +
	"(SELECT\n" +
	"ORDER_ID,  PRODUCT_ID, (PRODUCT_PRICE/10000) PRODUCT_PRICE\n" +
	"FROM KRC_PRODUCT_AVAIL\n" +
	"WHERE  QUANTITY>0 AND PRODUCT_ID =$1\n" +
	"AND USER_MODIFY_ID=$2\n" +
	") MARCADOS\n" +
	"INNER JOIN KRC_PRODUCT ON (MARCADOS.PRODUCT_ID = KRC_PRODUCT.PRODUCT_ID)\n" +
	"INNER JOIN KRC_PRODUCT_TYPE ON (KRC_PRODUCT.PRODUCT_TYPE_ID = KRC_PRODUCT_TYPE.PRODUCT_TYPE_ID)\n" +
	"INNER JOIN KRF_TRANSACTIONS ON (KRF_TRANSACTIONS.ORDER_ID = MARCADOS.ORDER_ID)\n" +
	"INNER JOIN KRC_BANK_ACCOUNT ON (KRF_TRANSACTIONS.BANK_ACCOUNT_ID = KRC_BANK_ACCOUNT.BANK_ACCOUNT_ID);";
	return sql_query;
}
//
// Discount of KRC_PRODUCT_AVAIL the products which have been marked in the first step
// 
export function updateStockProductAvail (): string {
	const sql_update = "UPDATE KRC_PRODUCT_AVAIL SET QUANTITY=0 WHERE QUANTITY>0 AND PRODUCT_ID =$1  and USER_MODIFY_ID=$2;"
	return sql_update;
}
//
// get the default logistic address for a user
//
export function getDefaultLogisticAddress(): string {
    const sql_query = `SELECT
    ADDR.ADDR_ID
    , ADDR.ADDR_STREET
    , ADDR.ADDR_NUMBER
    , ADDR.ADDR_COMPLEMENT
    , ADDR.SUBURB
    , ADDR.DISTRICT
    , ADDR.CITY
    , ADDR.PROVINCE
    , ADDR.STATE
    , ADDR.COUNTRY
    , ADDR.ADDR_ZIP_CODE
    , ADDR.INDICATION
    , ADDR.STATUS_ID
    FROM KRC_ADDRESS ADDR
    INNER JOIN KRC_PERSONE_IDENTITY PER
    ON (ADDR.ADDR_OBJECT = PER.PERSONE_ID AND ADDR.ADDR_TYPE = 'L' AND ADDR.STATUS_ID = 'D')
    INNER JOIN  KRC_USER USER
    ON (PER.USER_ID = USER.USER_ID)
    WHERE USER.USER_ID = $1;`;
    return sql_query;
}
//
// get the default logistic address for a user by persone_id
//
export function getDefaultLogisticAddressByPersoneId(): string {
    const sql_query = `SELECT
    ADDR.ADDR_ID
    , ADDR.ADDR_STREET
    , ADDR.ADDR_NUMBER
    , ADDR.ADDR_COMPLEMENT
    , ADDR.SUBURB
    , ADDR.DISTRICT
    , ADDR.CITY
    , ADDR.PROVINCE
    , ADDR.STATE
    , ADDR.COUNTRY
    , ADDR.ADDR_ZIP_CODE
    , ADDR.INDICATION
    , ADDR.STATUS_ID
    FROM KRC_ADDRESS ADDR
    INNER JOIN KRC_PERSONE_IDENTITY PER
    ON (ADDR.ADDR_OBJECT = PER.PERSONE_ID AND ADDR.ADDR_TYPE = 'L' AND ADDR.STATUS_ID = 'D')
    WHERE PER.PERSONE_ID = $1;`;
    return sql_query;
}
//
// get the ROLE of the user
//
export function getRoleByUser (): string {
    const sql_query = "SELECT " +
    "C.ROLE_NAME ROLE_NAME " +
    "FROM " + 
    "KRC_USER A, KRR_USER_ROLE B, KRC_ROLE C " +
    "WHERE " + 
    "A.USER_ID = B.USER_ID AND B.ROLE_ID = C.ROLE_ID " + 
    "AND A.USER_ID = $1;";
    return sql_query;
}
//
// get all the addresses for a PERSONE_ID
//
export function getAdresses(): string {
    const sql_query = `SELECT
    ADDR.ADDR_ID
    , ADDR.ADDR_STREET
    , ADDR.ADDR_NUMBER
    , ADDR.ADDR_COMPLEMENT
    , ADDR.SUBURB
    , ADDR.DISTRICT
    , ADDR.CITY
    , ADDR.PROVINCE
    , ADDR.STATE
    , ADDR.COUNTRY
    , ADDR.ADDR_ZIP_CODE
    , ADDR.INDICATION
    , ADDR.STATUS_ID
    FROM KRC_ADDRESS ADDR
    INNER JOIN KRC_PERSONE_IDENTITY PER
    ON (ADDR.ADDR_OBJECT = PER.PERSONE_ID AND ADDR.ADDR_TYPE = 'L')
    WHERE PER.PERSONE_ID = $1;`;
    return sql_query;
}
