//
// Retorna todos los productos que se encuentran en la tabla KRC_PRODUCTS
// con todos los JOINs
//
export function getProducts (): string {
    const query = 
    `SELECT
        PROD.PRODUCT_ID
        , PROD.PRODUCT_CODE
        , PROD.PRODUCT_CATEGORY_ID
        , CAT.PRODUCT_CATEGORY
        , PROD.PRODUCT_NAME
        , PROD.PRODUCT_NAME_INTERNAL
        , PROD.PRODUCT_DESCRIPTION
        , PROD.BRAND_ID
        , BRAND.BRAND
        , PROD.MIN_QUANTITY_SELL
        , PROD.LANGUAGE_CODE
        , PROD.PRODUCT_PRICE
        , PROD.TAX_ID
        , PROD.CURRENCY_ID
        , PROD.UNIT_ID
        , DMD_UNIT.DES_UNIT
        , PROD.WEEKS_WARNING
        , PROD.QUANTITY_MIN_PRICE
        , PROD.QUANTITY_MAX_PRICE
        , PROD.TYPE_DAY_DELIVERY
        , DMD_DELIVERY_TYPE.DES_DELIVERY_TYPE
        , PROD.MIN_DAYS_DELIVERY
        , PROD.MAX_DAYS_DELIVERY
        , PROD.REMARK
        , PROD.DAYS_DELIVERY
        , PROD.PRODUCT_TYPE_ID
        , PROD.PROVIDER_ID
        , PERSONE.PERSONE_NAME
        , PROD.PARTNER_ID
        , PARTNER.PERSONE_NAME PARTNER_NAME
        , PROD.EFF_DATE
        , PROD.EXP_DATE
        , PROD.DAYS_EXP
        , PROD.EXPOILED_FLAG
        , PROD.COUNTABLE_FLAG
        , PROD.SOURCE_ID
        , PROD.NUM_IMAGES
        , PROD.NUM_VIDEOS
    FROM
        KRC_PRODUCT PROD
        LEFT JOIN KRC_PRODUCT_CATEGORY CAT
        ON (CAT.PRODUCT_CATEGORY_ID = PROD.PRODUCT_CATEGORY_ID AND CAT.STATUS_ID = 'A' )
        LEFT OUTER JOIN KRC_BRAND BRAND
        ON (BRAND.BRAND_ID = PROD.BRAND_ID AND BRAND.STATUS_ID = 'A')
        LEFT OUTER JOIN KRC_TAX_TYPE TAX
        ON (TAX.TAX_ID = PROD.TAX_ID)
        LEFT OUTER JOIN DMD_UNIT
        ON (DMD_UNIT.CVE_UNIT = PROD.UNIT_ID)
        LEFT OUTER JOIN DMD_DELIVERY_TYPE
        ON (PROD.TYPE_DAY_DELIVERY = DMD_DELIVERY_TYPE.CVE_DELIVERY_TYPE)
        LEFT OUTER JOIN KRC_PRODUCT_TYPE PRODUCT_TYPE
        ON (PROD.PRODUCT_TYPE_ID = PRODUCT_TYPE.PRODUCT_TYPE_ID)
        LEFT OUTER JOIN KRC_PERSONE_IDENTITY PERSONE
        ON (PROD.PROVIDER_ID = PERSONE.PERSONE_ID AND PERSONE.STATUS_ID = 'A')
        LEFT OUTER JOIN KRC_PERSONE_IDENTITY PARTNER
        ON (PROD.PARTNER_ID = PARTNER.PERSONE_ID AND PARTNER.STATUS_ID = 'A')
    WHERE
        PROD.STATUS_ID = 'A'
    ;`;
    return query;
}